/*
 * @file axiom_pkg_serialize.c
 * @brief Axiom package system - save, content hash, dependency validation
 * @details Split from axiom_pkg.c
 */

#include "axiom_pkg.h"
#include "axiom_pkg_internal.h"

#include "lv/lv_file.h"

#include <ctype.h>
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lv/sha256.h"

#include "debug.h"
#include "error_codes.h"
#include "lexer_shared.h"
#include "lv_internal.h"
#include "lv_utils.h"
#include "stream.h"

/* ============== 保存功能 ============== */

static const char *behavior_to_string(int behavior) {
    switch (behavior) {
        case CONSTRUCTIVE:
            return "constructive";
        case NON_CONSTRUCTIVE_ORACLE:
            return "non_constructive_oracle";
        case EXPLOSION_PRINCIPLE:
        default:
            return "explosion_principle";
    }
}

AxiomSaveStatus axiom_package_save(const AxiomPackage *pkg, const char *filepath) {
    if (!pkg || !filepath)
        return AXIOM_SAVE_FILE_ERROR;

    FILE *f = lv_file_open(filepath, "w");
    if (!f) {
        lv_set_error(lv_ERROR_IO, "无法创建文件: %s", filepath);
        return AXIOM_SAVE_FILE_ERROR;
    }

    /* 写入文件头注释 */
    fprintf(f, "# Axiom Package File\n");
    fprintf(f, "# Generated by axiom_package_save\n\n");

    /* 写入包声明 */
    fprintf(f, "axiom \"%s\" \"%s\" {\n", pkg->name ? pkg->name : "unnamed", pkg->version ? pkg->version : "0.0.0");

    /* 写入模板 */
    for (int i = 0; i < pkg->templates.count; i++) {
        ConstraintTemplate *t = (ConstraintTemplate *)lv_darray_get(&pkg->templates, i);
        fprintf(f, "    template \"%s\" %d\n", t->name, t->param_count);
    }

    /* 写入不可构造问题 */
    for (int i = 0; i < pkg->known_unconstructibles.count; i++) {
        KnownUnconstructible *uc = (KnownUnconstructible *)lv_darray_get(&pkg->known_unconstructibles, i);
        fprintf(f, "\n    unconstructible \"%s\" {\n", uc->name);

        if (uc->reduces_to) {
            fprintf(f, "        reduces_to \"%s\"\n", uc->reduces_to);
        }

        for (int j = 0; j < uc->dependency_chain.count; j++) {
            fprintf(f, "        dependency \"%s\"\n", *(char **)lv_darray_get(&uc->dependency_chain, j));
        }

        if (uc->external_ref) {
            fprintf(f, "        external_ref \"%s\"\n", uc->external_ref);
        }

        fprintf(f, "        green_verified %s\n", uc->green_verified ? "true" : "false");
        fprintf(f, "    }\n");
    }

    /* 写入其他属性 */
    if (pkg->bottom_geometry) {
        fprintf(f, "\n    bottom_geometry \"%s\"\n", pkg->bottom_geometry);
    }

    if (pkg->negation_encoding) {
        fprintf(f, "    negation_encoding \"%s\"\n", pkg->negation_encoding);
    }

    fprintf(f, "    contradiction_behavior \"%s\"\n", behavior_to_string(pkg->contradiction_behavior));

    /* 关闭包 */
    fprintf(f, "}\n");

    lv_file_close(f);

    if (axiom_stream_ctx) {
        stream_emit_simple(axiom_stream_ctx, STREAM_EVENT_INFO, "公理包保存成功", 0);
    }

    return AXIOM_SAVE_OK;
}

/* ============== 内容哈希 (SHA-256) ============== */

char *axiom_package_compute_content_hash(AxiomPackage *pkg) {
    if (!pkg)
        lv_RETURN_ERROR_NULL(lv_ERROR_NULL_POINTER, "axiom_package_compute_content_hash: pkg is NULL");

    lvSha256Context ctx;
    lv_sha256_init(&ctx);

    /* 哈希名称和版本：sha256_hash_string 语义 */
    if (pkg->name) {
        lv_sha256_update(&ctx, (const uint8_t *) pkg->name, strlen(pkg->name));
    } else {
        lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
    }
    if (pkg->version) {
        lv_sha256_update(&ctx, (const uint8_t *) pkg->version, strlen(pkg->version));
    } else {
        lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
    }

    /* 哈希所有模板名称和参数数量 */
    for (int i = 0; i < pkg->templates.count; i++) {
        ConstraintTemplate *t = (ConstraintTemplate *)lv_darray_get(&pkg->templates, i);
        if (t->name) {
            lv_sha256_update(&ctx, (const uint8_t *) t->name, strlen(t->name));
        } else {
            lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
        }
        lv_sha256_update(&ctx, (const uint8_t *) &t->param_count, sizeof(int));
        lv_sha256_update(&ctx, (const uint8_t *) &t->verified, sizeof(bool));
    }

    /* 哈希所有不可构造问题 */
    for (int i = 0; i < pkg->known_unconstructibles.count; i++) {
        KnownUnconstructible *uc = (KnownUnconstructible *)lv_darray_get(&pkg->known_unconstructibles, i);

        if (uc->name) {
            lv_sha256_update(&ctx, (const uint8_t *) uc->name, strlen(uc->name));
        } else {
            lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
        }
        if (uc->reduces_to) {
            lv_sha256_update(&ctx, (const uint8_t *) uc->reduces_to, strlen(uc->reduces_to));
        } else {
            lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
        }

        /* 哈希依赖链 */
        for (int j = 0; j < uc->dependency_chain.count; j++) {
            char *dep = *(char **)lv_darray_get(&uc->dependency_chain, j);
            if (dep) {
                lv_sha256_update(&ctx, (const uint8_t *) dep, strlen(dep));
            } else {
                lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
            }
        }

        if (uc->external_ref) {
            lv_sha256_update(&ctx, (const uint8_t *) uc->external_ref, strlen(uc->external_ref));
        } else {
            lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
        }
        lv_sha256_update(&ctx, (const uint8_t *) &uc->green_verified, sizeof(bool));
    }

    /* 哈希其他属性 */
    if (pkg->bottom_geometry) {
        lv_sha256_update(&ctx, (const uint8_t *) pkg->bottom_geometry, strlen(pkg->bottom_geometry));
    } else {
        lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
    }
    if (pkg->negation_encoding) {
        lv_sha256_update(&ctx, (const uint8_t *) pkg->negation_encoding, strlen(pkg->negation_encoding));
    } else {
        lv_sha256_update(&ctx, (const uint8_t *) "(null)", 6);
    }
    lv_sha256_update(&ctx, (const uint8_t *) &pkg->contradiction_behavior, sizeof(int));

    /* 计算最终哈希 */
    uint8_t hash[AXIOM_SHA256_OUTPUT_SIZE];
    lv_sha256_final(&ctx, hash);

    /* 转换为十六进制字符串（64个字符 + 空终止符） */
    char *result = lv_malloc(AXIOM_SHA256_HEX_SIZE);
    if (result) {
        for (int i = 0; i < AXIOM_SHA256_OUTPUT_SIZE; i++) {
            snprintf(result + i * 2, 3, "%02x", hash[i]);
        }
        result[AXIOM_SHA256_HEX_SIZE - 1] = '\0';
    }

    return result;
}

/* ============== 依赖验证 ============== */

/* 检查字符串是否为有效的URL格式 */
static bool is_valid_url(const char *str) {
    if (!str || !*str)
        return false;

    /* 检查常见URL协议 */
    if (strncmp(str, "http://", 7) == 0)
        return true;
    if (strncmp(str, "https://", 8) == 0)
        return true;
    if (strncmp(str, "ftp://", 6) == 0)
        return true;
    if (strncmp(str, "file://", 7) == 0)
        return true;

    /* 检查DOI格式 */
    if (strncmp(str, "doi:", 4) == 0)
        return true;

    /* 检查arXiv格式 */
    if (strncmp(str, "arXiv:", 6) == 0)
        return true;

    /* 检查标识符格式 (字母开头，只包含字母数字、下划线、连字符、点) */
    if (isalpha((unsigned char) str[0])) {
        for (const char *p = str + 1; *p; p++) {
            if (!isalnum((unsigned char) *p) && *p != '_' && *p != '-' && *p != '.') {
                return false;
            }
        }
        return true;
    }

    return false;
}

/* 在已加载的包中查找问题 */
static KnownUnconstructible *find_problem_in_packages(AxiomPackage **packages, int package_count,
                                                      const char *problem_name) {
    if (!packages || !problem_name)
        return NULL;

    for (int i = 0; i < package_count; i++) {
        AxiomPackage *pkg = packages[i];
        if (!pkg)
            continue;

        KnownUnconstructible *uc = axiom_package_lookup_unconstructible(pkg, problem_name);
        if (uc)
            return uc;
    }

    return NULL;
}

/* 在已加载的包中查找模板 */
static ConstraintTemplate *find_template_in_packages(AxiomPackage **packages, int package_count,
                                                     const char *template_name) {
    if (!packages || !template_name)
        return NULL;

    for (int i = 0; i < package_count; i++) {
        AxiomPackage *pkg = packages[i];
        if (!pkg)
            continue;

        ConstraintTemplate *tmpl = axiom_package_get_template(pkg, template_name);
        if (tmpl)
            return tmpl;
    }

    return NULL;
}

bool axiom_package_validate_dependencies(AxiomPackage *pkg, AxiomPackage **loaded_packages, int package_count) {
    if (!pkg) {
        lv_set_error(lv_ERROR_INVALID_PARAM, "无效参数: 包为空");
        return false;
    }

    lv_clear_error();

    bool all_valid = true;

    for (int i = 0; i < pkg->known_unconstructibles.count; i++) {
        KnownUnconstructible *uc = (KnownUnconstructible *)lv_darray_get(&pkg->known_unconstructibles, i);

        /* 验证 reduces_to 引用 */
        if (uc->reduces_to && uc->reduces_to[0] != '\0') {
            KnownUnconstructible *target = find_problem_in_packages(loaded_packages, package_count, uc->reduces_to);

            /* 也检查当前包 */
            if (!target) {
                target = axiom_package_lookup_unconstructible(pkg, uc->reduces_to);
            }

            if (!target) {
                lv_set_error(lv_ERROR_NOT_FOUND, "依赖验证失败: 问题 '%s' 的 reduces_to '%s' 未找到", uc->name,
                             uc->reduces_to);
                all_valid = false;
                /* 继续检查其他问题 */
            }
        }

        /* 验证依赖链中的所有项 */
        for (int j = 0; j < uc->dependency_chain.count; j++) {
            const char *dep = *(char **)lv_darray_get(&uc->dependency_chain, j);

            /* 检查是否为已知问题 */
            KnownUnconstructible *dep_problem = find_problem_in_packages(loaded_packages, package_count, dep);

            if (!dep_problem) {
                dep_problem = axiom_package_lookup_unconstructible(pkg, dep);
            }

            /* 检查是否为已知模板 */
            ConstraintTemplate *dep_template = find_template_in_packages(loaded_packages, package_count, dep);

            /* 回退：在当前包中查找模板 */
            if (!dep_template) {
                dep_template = axiom_package_get_template(pkg, dep);
            }

            if (!dep_problem && !dep_template) {
                lv_set_error(lv_ERROR_NOT_FOUND, "依赖验证失败: 问题 '%s' 的依赖 '%s' 未在任何已加载的包中找到",
                             uc->name, dep);
                all_valid = false;
            }
        }

        /* 验证外部引用格式 */
        if (uc->external_ref && uc->external_ref[0] != '\0') {
            if (!is_valid_url(uc->external_ref)) {
                lv_set_error(lv_ERROR_INVALID_PARAM,
                             "依赖验证失败: 问题 '%s' 的 external_ref '%s' 不是有效的URL或标识符格式", uc->name,
                             uc->external_ref);
                all_valid = false;
            }
        }
    }

    return all_valid;
}
