import sys

path = r'c:\Users\xingg\Desktop\知识体系化Wiki\Lv-00\core\src\layer4_reasoning\backends\groebner_engine_poly.c'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. poly_destroy
old = ("void poly_destroy(lvRingRegistry *registry, int poly_id) {\n"
    "    lv_UNUSED(registry);\n"
    "    lv_mutex_lock(&g_data_mutex);\n"
    "    if (!g_data || poly_id < 0 || poly_id >= g_data->poly_count) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    if (g_data->polys[poly_id]) {\n"
    "        poly_internal_destroy(g_data->polys[poly_id]);\n"
    "        g_data->polys[poly_id] = NULL;\n"
    "    }\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "}")
new = ("void poly_destroy(lvRingRegistry *registry, int poly_id) {\n"
    "    lv_UNUSED(registry);\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    if (!g_data || poly_id < 0 || poly_id >= g_data->poly_count)\n"
    "        goto cleanup;\n"
    "\n"
    "    if (g_data->polys[poly_id]) {\n"
    "        poly_internal_destroy(g_data->polys[poly_id]);\n"
    "        g_data->polys[poly_id] = NULL;\n"
    "    }\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_destroy: OK')
else:
    print('poly_destroy: FAILED')

# 2. poly_get
old = ("const lvPolynomial *poly_get(const lvRingRegistry *registry, int poly_id) {\n"
    "    lv_UNUSED(registry);\n"
    "    lv_mutex_lock(&g_data_mutex);\n"
    "    if (!g_data || poly_id < 0 || poly_id >= g_data->poly_count) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return NULL;\n"
    "    }\n"
    "    const lvPolynomial *p = g_data->polys[poly_id];\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "    return p;\n"
    "}")
new = ("const lvPolynomial *poly_get(const lvRingRegistry *registry, int poly_id) {\n"
    "    lv_UNUSED(registry);\n"
    "    const lvPolynomial *p = NULL;\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    if (!g_data || poly_id < 0 || poly_id >= g_data->poly_count)\n"
    "        goto cleanup;\n"
    "    p = g_data->polys[poly_id];\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return p;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_get: OK')
else:
    print('poly_get: FAILED')

# 3. poly_create locked section
old = ("    lv_mutex_lock(&g_data_mutex);\n"
    "    lvRegistryData *data = registry_data_ensure();\n"
    "    if (!data) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        poly_internal_destroy(poly);\n"
    '        lv_RETURN_ERROR(lv_ERROR_INTERNAL, "poly_create: registry_data_ensure failed");\n'
    "    }\n"
    "\n"
    "    int result = poly_internal_store(data, poly);\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "    return result;\n"
    "}")
new = ("    int ret = -1;\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    lvRegistryData *data = registry_data_ensure();\n"
    "    if (!data) {\n"
    "        poly_internal_destroy(poly);\n"
    '        lv_set_error_ctx(lv_ERROR_INTERNAL, __FILE__, __LINE__, __func__,\n'
    '                         "poly_create: registry_data_ensure failed");\n'
    "        goto cleanup;\n"
    "    }\n"
    "\n"
    "    ret = poly_internal_store(data, poly);\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return ret;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_create: OK')
else:
    print('poly_create: FAILED')

# 4. poly_add
old = ("int poly_add(lvRingRegistry *registry, int poly_id_f, int poly_id_g, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    lv_mutex_lock(&g_data_mutex);\n"
    "    if (!g_data) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id_f < 0 || poly_id_g < 0) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id_f >= g_data->poly_count || poly_id_g >= g_data->poly_count) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id_f];\n"
    "    lvPolynomial *g = g_data->polys[poly_id_g];\n"
    "    if (!f || !g) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    if (f->ring_id != g->ring_id) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *result = poly_internal_add(f, g, ring);\n"
    "    if (!result) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    int ret = poly_internal_store(g_data, result);\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "    return ret;\n"
    "}")
new = ("int poly_add(lvRingRegistry *registry, int poly_id_f, int poly_id_g, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    int ret = -1;\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    if (!g_data)\n"
    "        goto cleanup;\n"
    "    if (poly_id_f < 0 || poly_id_g < 0)\n"
    "        goto cleanup;\n"
    "    if (poly_id_f >= g_data->poly_count || poly_id_g >= g_data->poly_count)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id_f];\n"
    "    lvPolynomial *g = g_data->polys[poly_id_g];\n"
    "    if (!f || !g)\n"
    "        goto cleanup;\n"
    "\n"
    "    if (f->ring_id != g->ring_id)\n"
    "        goto cleanup;\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *result = poly_internal_add(f, g, ring);\n"
    "    if (!result)\n"
    "        goto cleanup;\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    ret = poly_internal_store(g_data, result);\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return ret;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_add: OK')
else:
    print('poly_add: FAILED')

# 5. poly_multiply
old = ("int poly_multiply(lvRingRegistry *registry, int poly_id_f, int poly_id_g, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    lv_mutex_lock(&g_data_mutex);\n"
    "    if (!g_data) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id_f < 0 || poly_id_g < 0) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id_f >= g_data->poly_count || poly_id_g >= g_data->poly_count) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id_f];\n"
    "    lvPolynomial *g = g_data->polys[poly_id_g];\n"
    "    if (!f || !g) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    if (f->ring_id != g->ring_id) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *result = poly_internal_multiply(f, g, ring);\n"
    "    if (!result) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    int ret = poly_internal_store(g_data, result);\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "    return ret;\n"
    "}")
new = ("int poly_multiply(lvRingRegistry *registry, int poly_id_f, int poly_id_g, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    int ret = -1;\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    if (!g_data)\n"
    "        goto cleanup;\n"
    "    if (poly_id_f < 0 || poly_id_g < 0)\n"
    "        goto cleanup;\n"
    "    if (poly_id_f >= g_data->poly_count || poly_id_g >= g_data->poly_count)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id_f];\n"
    "    lvPolynomial *g = g_data->polys[poly_id_g];\n"
    "    if (!f || !g)\n"
    "        goto cleanup;\n"
    "\n"
    "    if (f->ring_id != g->ring_id)\n"
    "        goto cleanup;\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *result = poly_internal_multiply(f, g, ring);\n"
    "    if (!result)\n"
    "        goto cleanup;\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    ret = poly_internal_store(g_data, result);\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return ret;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_multiply: OK')
else:
    print('poly_multiply: FAILED')

# 6. poly_substitute
old = ("int poly_substitute(lvRingRegistry *registry, int poly_id, int var_index, int subst_poly_id, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    lv_mutex_lock(&g_data_mutex);\n"
    "    if (!g_data) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id < 0 || subst_poly_id < 0) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    if (poly_id >= g_data->poly_count || subst_poly_id >= g_data->poly_count) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id];\n"
    "    lvPolynomial *subst = g_data->polys[subst_poly_id];\n"
    "    if (!f || !subst) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    if (f->ring_id != subst->ring_id) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lvPolynomial *result = poly_internal_substitute(f, var_index, subst, ring);\n"
    "    if (!result) {\n"
    "        lv_mutex_unlock(&g_data_mutex);\n"
    "        return -1;\n"
    "    }\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    int ret = poly_internal_store(g_data, result);\n"
    "    lv_mutex_unlock(&g_data_mutex);\n"
    "    return ret;\n"
    "}")
new = ("int poly_substitute(lvRingRegistry *registry, int poly_id, int var_index, int subst_poly_id, const char *result_label) {\n"
    "    if (!registry)\n"
    "        return -1;\n"
    "\n"
    "    int ret = -1;\n"
    "    lvLockGuard _lg;\n"
    "    lv_lock_guard_init(&_lg, &g_data_mutex);\n"
    "    if (!g_data)\n"
    "        goto cleanup;\n"
    "    if (poly_id < 0 || subst_poly_id < 0)\n"
    "        goto cleanup;\n"
    "    if (poly_id >= g_data->poly_count || subst_poly_id >= g_data->poly_count)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *f = g_data->polys[poly_id];\n"
    "    lvPolynomial *subst = g_data->polys[subst_poly_id];\n"
    "    if (!f || !subst)\n"
    "        goto cleanup;\n"
    "\n"
    "    if (f->ring_id != subst->ring_id)\n"
    "        goto cleanup;\n"
    "    lvPolynomialRing *ring = registry->rings[f->ring_id];\n"
    "    if (!ring)\n"
    "        goto cleanup;\n"
    "\n"
    "    lvPolynomial *result = poly_internal_substitute(f, var_index, subst, ring);\n"
    "    if (!result)\n"
    "        goto cleanup;\n"
    "\n"
    "    lv_free((void **) &result->label);\n"
    "    result->label = groebner_strdup_safe(result_label);\n"
    "\n"
    "    ret = poly_internal_store(g_data, result);\n"
    "cleanup:\n"
    "    lv_lock_guard_destroy(&_lg);\n"
    "    return ret;\n"
    "}")
if old in content:
    content = content.replace(old, new, 1)
    print('poly_substitute: OK')
else:
    print('poly_substitute: FAILED')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('All done')