/**
 * @file ga_codegen.c
 * @brief Implementation of GA code generator
 *
 * Translates multivector expressions into target programming languages.
 * Provides simple string-based code generation for C, C++, CUDA, LaTeX,
 * Python, and DOT output formats.
 *
 * @version 1.0.0
 */

#include "ga_codegen.h"
#include "ga_multivector.h"
#include "lv00_utils.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

/* ========================================================================
 * Internal helpers
 * ======================================================================== */

/** @brief Blade names used in code generation */
static const char *g_codegen_blade_names[GA_MV_DIM] = {
    "1",       "e1",    "e2",    "e3",    "e0",
    "e12",     "e13",   "e03",   "e23",   "e023",
    "e123",    "e0123", "e013",  "e0234", "e01234",
    "e1234"
};

/**
 * @brief Append a string to a dynamically growing buffer
 */
static int buf_append(char **buf, size_t *capacity, size_t *len, const char *str) {
    size_t str_len = strlen(str);
    while (*len + str_len + 1 > *capacity) {
        *capacity *= 2;
        char *new_buf = (char *)lv00_malloc(*capacity);
        if (!new_buf) return -1;
        memcpy(new_buf, *buf, *len);
        new_buf[*len] = '\0';
        lv00_free((void **)buf);
        *buf = new_buf;
    }
    memcpy(*buf + *len, str, str_len + 1);
    *len += str_len;
    return 0;
}

/**
 * @brief Count the number of lines in a string
 */
static int count_lines(const char *str) {
    if (!str) return 0;
    int count = 1;
    for (const char *p = str; *p; p++) {
        if (*p == '\n') count++;
    }
    return count;
}

/* ========================================================================
 * Code Generation
 * ======================================================================== */

GACodegenResult *ga_codegen_compile(const Lv00MultiVector *mv,
                                     const GACodegenOptions *options) {
    GACodegenResult *result = (GACodegenResult *)lv00_malloc(sizeof(GACodegenResult));
    if (!result) return NULL;
    memset(result, 0, sizeof(GACodegenResult));

    if (!mv) {
        result->error_msg = (char *)lv00_malloc(32);
        if (result->error_msg) snprintf(result->error_msg, 32, "Error: mv is NULL");
        return result;
    }

    const char *var_name = (options && options->variable_name) ? options->variable_name : "mv";
    const char *indent = (options && options->indent) ? options->indent : "    ";
    GACodegenTarget target = options ? options->target : GA_CODEGEN_C;

    result->target = target;

    size_t capacity = 1024;
    size_t len = 0;
    char *code = (char *)lv00_malloc(capacity);
    if (!code) {
        result->error_msg = (char *)lv00_malloc(32);
        if (result->error_msg) snprintf(result->error_msg, 32, "Error: allocation failed");
        return result;
    }
    code[0] = '\0';

    /* Generate header comment */
    if (!options || options->include_header) {
        buf_append(&code, &capacity, &len, "/* Generated by Lv-00 GA Codegen */\n");
    }

    switch (target) {
        case GA_CODEGEN_C:
        case GA_CODEGEN_CPP: {
            const char *type = (target == GA_CODEGEN_CPP) ? "double" : "double";
            buf_append(&code, &capacity, &len, type);
            buf_append(&code, &capacity, &len, " ");
            buf_append(&code, &capacity, &len, var_name);
            buf_append(&code, &capacity, &len, "[16] = {");

            int first = 1;
            for (int i = 0; i < GA_MV_DIM; i++) {
                if (!first) buf_append(&code, &capacity, &len, ", ");
                char tmp[64];
                snprintf(tmp, sizeof(tmp), "%.10g", mv->components[i]);
                buf_append(&code, &capacity, &len, tmp);
                first = 0;
            }
            buf_append(&code, &capacity, &len, "};\n");

            /* Add named component accessors */
            buf_append(&code, &capacity, &len, "/* Blade components: */\n");
            for (int i = 0; i < GA_MV_DIM; i++) {
                if (fabs(mv->components[i]) > 1e-15) {
                    char tmp[128];
                    snprintf(tmp, sizeof(tmp), "%s/* %s = %.10g */\n",
                             indent, g_codegen_blade_names[i], mv->components[i]);
                    buf_append(&code, &capacity, &len, tmp);
                }
            }
            break;
        }

        case GA_CODEGEN_CUDA: {
            buf_append(&code, &capacity, &len, "__device__ double ");
            buf_append(&code, &capacity, &len, var_name);
            buf_append(&code, &capacity, &len, "[16] = {");

            int first = 1;
            for (int i = 0; i < GA_MV_DIM; i++) {
                if (!first) buf_append(&code, &capacity, &len, ", ");
                char tmp[64];
                snprintf(tmp, sizeof(tmp), "%.10g", mv->components[i]);
                buf_append(&code, &capacity, &len, tmp);
                first = 0;
            }
            buf_append(&code, &capacity, &len, "};\n");
            break;
        }

        case GA_CODEGEN_PYTHON: {
            buf_append(&code, &capacity, &len, "import numpy as np\n\n");
            buf_append(&code, &capacity, &len, var_name);
            buf_append(&code, &capacity, &len, " = np.array([");

            int first = 1;
            for (int i = 0; i < GA_MV_DIM; i++) {
                if (!first) buf_append(&code, &capacity, &len, ", ");
                char tmp[64];
                snprintf(tmp, sizeof(tmp), "%.10g", mv->components[i]);
                buf_append(&code, &capacity, &len, tmp);
                first = 0;
            }
            buf_append(&code, &capacity, &len, "])\n");
            break;
        }

        case GA_CODEGEN_LATEX: {
            /* Delegate to ga_render_latex */
            char *latex = ga_render_latex(mv);
            if (latex) {
                buf_append(&code, &capacity, &len, latex);
                lv00_free_ptr(latex);
            }
            break;
        }

        case GA_CODEGEN_DOT: {
            /* Delegate to ga_render_dot */
            char *dot = ga_render_dot(mv);
            if (dot) {
                buf_append(&code, &capacity, &len, dot);
                lv00_free_ptr(dot);
            }
            break;
        }
    }

    result->code = code;
    result->line_count = count_lines(code);
    return result;
}

void ga_codegen_result_destroy(GACodegenResult *result) {
    if (!result) return;
    if (result->code) lv00_free((void **)&result->code);
    if (result->error_msg) lv00_free((void **)&result->error_msg);
    lv00_free((void **)&result);
}

/* ========================================================================
 * Rendering Functions
 * ======================================================================== */

char *ga_render_latex(const Lv00MultiVector *mv) {
    if (!mv) return NULL;

    size_t capacity = 512;
    size_t len = 0;
    char *buf = (char *)lv00_malloc(capacity);
    if (!buf) return NULL;
    buf[0] = '\0';

    int first_term = 1;

    for (int i = 0; i < GA_MV_DIM; i++) {
        double val = mv->components[i];
        if (fabs(val) < 1e-15) continue;

        char term[128];

        if (i == 0) {
            /* Scalar component */
            snprintf(term, sizeof(term), "%.4g", val);
        } else {
            /* Blade component */
            if (first_term) {
                if (fabs(val - 1.0) < 1e-10) {
                    snprintf(term, sizeof(term), "%s", g_codegen_blade_names[i]);
                } else if (fabs(val + 1.0) < 1e-10) {
                    snprintf(term, sizeof(term), "-%s", g_codegen_blade_names[i]);
                } else {
                    snprintf(term, sizeof(term), "%.4g\\,%s", val, g_codegen_blade_names[i]);
                }
            } else {
                if (val > 0) {
                    if (fabs(val - 1.0) < 1e-10) {
                        snprintf(term, sizeof(term), " + %s", g_codegen_blade_names[i]);
                    } else {
                        snprintf(term, sizeof(term), " + %.4g\\,%s", val, g_codegen_blade_names[i]);
                    }
                } else {
                    if (fabs(val + 1.0) < 1e-10) {
                        snprintf(term, sizeof(term), " - %s", g_codegen_blade_names[i]);
                    } else {
                        snprintf(term, sizeof(term), " - %.4g\\,%s", -val, g_codegen_blade_names[i]);
                    }
                }
            }
        }

        buf_append(&buf, &capacity, &len, term);
        first_term = 0;
    }

    if (first_term) {
        buf_append(&buf, &capacity, &len, "0");
    }

    return buf;
}

char *ga_render_dot(const Lv00MultiVector *mv) {
    if (!mv) return NULL;

    size_t capacity = 512;
    size_t len = 0;
    char *buf = (char *)lv00_malloc(capacity);
    if (!buf) return NULL;
    buf[0] = '\0';

    buf_append(&buf, &capacity, &len, "digraph Multivector {\n");
    buf_append(&buf, &capacity, &len, "    node [shape=box];\n");
    buf_append(&buf, &capacity, &len, "    mv [label=\"Multivector\"];\n");

    int node_count = 0;
    for (int i = 0; i < GA_MV_DIM; i++) {
        if (fabs(mv->components[i]) < 1e-15) continue;

        char edge[256];
        snprintf(edge, sizeof(edge),
                 "    blade%d [label=\"%s = %.4g\"];\n"
                 "    mv -> blade%d;\n",
                 node_count, g_codegen_blade_names[i], mv->components[i], node_count);
        buf_append(&buf, &capacity, &len, edge);
        node_count++;
    }

    buf_append(&buf, &capacity, &len, "}\n");
    return buf;
}
