/**
 * @file lv_render_visitor_tikz.c
 * @brief TikZ 渲染后端 —— 基于 lvRenderVisitor 的实现
 *
 * 实现 lvRenderVisitor 的所有回调，生成 TikZ/LaTeX 绘图代码。
 *
 * @author Lv-00 Project
 * @version 1.0.0
 */

#include "lv/lv_render_visitor.h"
#include "lv/tikz_export.h"

#include <stdio.h>
#include <stdlib.h>

#include "lv/lv_file.h"

/* ========================================================================
 * 内部数据结构
 * ======================================================================== */

/** TikZ 后端私有上下文 */
typedef struct {
    FILE *fp;       /**< 输出文件指针 */
    int object_id;  /**< 对象计数器（生成唯一标签） */
} TikzContext;

/* ========================================================================
 * 颜色辅助
 * ======================================================================== */

/** 输出 TikZ 颜色定义 (draw= 或 fill= 前缀) */
static void tikz_write_color(FILE *fp, const float *color, const char *prefix) {
    fprintf(fp, "%s={rgb,1:red,%.3f;green,%.3f;blue,%.3f}",
            prefix, (double)color[0], (double)color[1], (double)color[2]);
}

/** 输出 TikZ 样式选项（描边 + 填充 + 虚线） */
static void tikz_write_style(FILE *fp, const lvVisualStyle *s, bool is_fill) {
    tikz_write_color(fp, s->stroke_color, is_fill ? "" : "draw");
    if (is_fill) {
        if (s->fill_color[3] > 0.0f) {
            fprintf(fp, ", fill={rgb,1:red,%.3f;green,%.3f;blue,%.3f}",
                    (double)s->fill_color[0], (double)s->fill_color[1], (double)s->fill_color[2]);
            fprintf(fp, ", fill opacity=%.2f", (double)s->fill_color[3]);
        }
    } else {
        fprintf(fp, ", draw opacity=%.2f", (double)s->stroke_color[3]);
    }
    fprintf(fp, ", line width=%.2fpt", (double)s->stroke_width);
    if (s->opacity < 1.0f)
        fprintf(fp, ", opacity=%.2f", (double)s->opacity);
    if (s->dashed)
        fprintf(fp, ", dashed");
}

/* ========================================================================
 * Visitor 回调实现
 * ======================================================================== */

static bool tikz_begin_scene(void *user_data, const char *title, int width, int height) {
    (void)width;
    (void)height;
    TikzContext *ctx = (TikzContext *)user_data;
    fprintf(ctx->fp, "%% %s\n", title);
    fprintf(ctx->fp, "%% Generated by Lv-00 Render Visitor (TikZ backend)\n");
    fprintf(ctx->fp, "\\begin{tikzpicture}[scale=1.0]\n");
    ctx->object_id = 0;
    return true;
}

static bool tikz_end_scene(void *user_data) {
    TikzContext *ctx = (TikzContext *)user_data;
    fprintf(ctx->fp, "\\end{tikzpicture}\n");
    return true;
}

static bool tikz_begin_group(void *user_data, const char *label) {
    TikzContext *ctx = (TikzContext *)user_data;
    fprintf(ctx->fp, "  %% begin group: %s\n", label);
    return true;
}

static bool tikz_end_group(void *user_data) {
    TikzContext *ctx = (TikzContext *)user_data;
    fprintf(ctx->fp, "  %% end group\n");
    return true;
}

static bool tikz_visit_point(void *user_data, double x, double y, const lvVisualStyle *style) {
    TikzContext *ctx = (TikzContext *)user_data;
    int id = ctx->object_id++;
    double r = (double)(style->stroke_width > 2.0f ? style->stroke_width : 3.0f);
    fprintf(ctx->fp, "  \\fill[");
    tikz_write_color(ctx->fp, style->stroke_color, "");
    fprintf(ctx->fp, "] (%.2f,%.2f) circle (%.2fpt);  %% point %d\n", x, y, r, id);
    return true;
}

static bool tikz_visit_segment(void *user_data, double x1, double y1, double x2, double y2,
                                const lvVisualStyle *style) {
    TikzContext *ctx = (TikzContext *)user_data;
    int id = ctx->object_id++;
    fprintf(ctx->fp, "  \\draw[");
    tikz_write_style(ctx->fp, style, false);
    fprintf(ctx->fp, "] (%.2f,%.2f) -- (%.2f,%.2f);  %% segment %d\n", x1, y1, x2, y2, id);
    return true;
}

static bool tikz_visit_line(void *user_data, double x1, double y1, double x2, double y2,
                             const lvVisualStyle *style) {
    TikzContext *ctx = (TikzContext *)user_data;
    int id = ctx->object_id++;
    fprintf(ctx->fp, "  \\draw[");
    tikz_write_style(ctx->fp, style, false);
    fprintf(ctx->fp, "] (%.2f,%.2f) -- (%.2f,%.2f);  %% line %d\n", x1, y1, x2, y2, id);
    return true;
}

static bool tikz_visit_circle(void *user_data, double cx, double cy, double r,
                               const lvVisualStyle *style) {
    TikzContext *ctx = (TikzContext *)user_data;
    int id = ctx->object_id++;
    fprintf(ctx->fp, "  \\draw[");
    tikz_write_style(ctx->fp, style, false);
    fprintf(ctx->fp, "] (%.2f,%.2f) circle (%.2f);  %% circle %d\n", cx, cy, r, id);
    return true;
}

static bool tikz_visit_polygon(void *user_data, const double *points, int point_count,
                                const lvVisualStyle *style) {
    TikzContext *ctx = (TikzContext *)user_data;
    int id = ctx->object_id++;
    fprintf(ctx->fp, "  \\draw[");
    tikz_write_style(ctx->fp, style, false);
    fprintf(ctx->fp, "] ");
    for (int j = 0; j < point_count; j++) {
        fprintf(ctx->fp, "(%.2f,%.2f)", points[j * 2], points[j * 2 + 1]);
        if (j < point_count - 1)
            fprintf(ctx->fp, " -- ");
    }
    fprintf(ctx->fp, " -- cycle;  %% polygon %d\n", id);
    return true;
}

/* ========================================================================
 * 公共 API
 * ======================================================================== */

/**
 * @brief 创建 TikZ 渲染访问器
 *
 * @param output_path 输出文件路径
 * @param visitor     [out] 填充好的 visitor 结构体
 * @return true  成功
 * @return false 文件打开失败
 */
bool lv_render_visitor_tikz_create(const char *output_path, lvRenderVisitor *visitor) {
    if (output_path == NULL || visitor == NULL)
        return false;

    FILE *fp = lv_file_open(output_path, "w");
    if (fp == NULL)
        return false;

    TikzContext *ctx = (TikzContext *)lv_malloc(sizeof(TikzContext));
    if (ctx == NULL) {
        lv_file_close(fp);
        return false;
    }
    ctx->fp = fp;
    ctx->object_id = 0;

    visitor->user_data   = ctx;
    visitor->begin_scene = tikz_begin_scene;
    visitor->end_scene   = tikz_end_scene;
    visitor->begin_group = tikz_begin_group;
    visitor->end_group   = tikz_end_group;
    visitor->visit_point   = tikz_visit_point;
    visitor->visit_segment = tikz_visit_segment;
    visitor->visit_line    = tikz_visit_line;
    visitor->visit_circle  = tikz_visit_circle;
    visitor->visit_polygon = tikz_visit_polygon;

    return true;
}

/**
 * @brief 销毁 TikZ 渲染访问器（关闭文件，释放内存）
 *
 * @param visitor 由 lv_render_visitor_tikz_create 填充的 visitor
 */
void lv_render_visitor_tikz_destroy(lvRenderVisitor *visitor) {
    if (visitor == NULL || visitor->user_data == NULL)
        return;
    TikzContext *ctx = (TikzContext *)visitor->user_data;
    if (ctx->fp)
        lv_file_close(ctx->fp);
    lv_free((void **) &ctx);
    visitor->user_data = NULL;
}
