/**
 * @file func_block_preset_data.c
 * @brief 内置预设元数据与全局状态
 *
 * 从 func_block_preset.c 拆分的模块之一。
 *
 * @version v5.0.0
 */

#include "func_block_preset_internal.h"
#include "lv/lv_xmacro.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "error_codes.h"
#include "lv_internal.h"
#include "lv_utils.h"

/** 预设库全局实例 */
PresetLibraryState g_preset_library = {
    .count = 0, .initialized = false, .next_preset_id = lv_PRESET_ID_OFFSET
};

/**
 * @brief 几何构造类预设元数据
 */
const PresetMetadata g_builtin_metadata[] = {
    /* ========== 基础构造 ========== */
    {.name = "midpoint",
     .description = "构造两点的中点",
     .mathematical_def = "M = \\frac{A + B}{2}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "centroid",
     .description = "构造三角形的重心",
     .mathematical_def = "G = \\frac{A + B + C}{3}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circumcenter",
     .description = "构造三角形的外心",
     .mathematical_def = "O \\text{ 满足 } |OA| = |OB| = |OC|",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 4,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "orthocenter",
     .description = "构造三角形的垂心",
     .mathematical_def = "H \\text{ 是三条高的交点}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 4,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "incenter",
     .description = "构造三角形的内心",
     .mathematical_def = "I = \\frac{aA + bB + cC}{a+b+c}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 4,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "excenter",
     .description = "构造三角形的旁心",
     .mathematical_def = "I_A = \\frac{-aA + bB + cC}{-a+b+c}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 直线构造 ========== */
    {.name = "line_through",
     .description = "过两点构造直线",
     .mathematical_def = "L = \\overleftrightarrow{AB}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "perpendicular_bisector",
     .description = "构造线段的垂直平分线",
     .mathematical_def = "L \\perp AB \\text{ 且过中点 } M",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 4,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "angle_bisector",
     .description = "构造角平分线",
     .mathematical_def = "L \\text{ 平分 } \\angle ABC",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "perpendicular_line",
     .description = "过点作直线的垂线",
     .mathematical_def = "L \\perp l \\text{ 且过点 } P",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "parallel_line",
     .description = "过点作直线的平行线",
     .mathematical_def = "L \\parallel l \\text{ 且过点 } P",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 圆构造 ========== */
    {.name = "circle_by_center_radius",
     .description = "以圆心和半径点构造圆",
     .mathematical_def = "C(O, r) \\text{ 其中 } r = |OP|",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circle_by_three_points",
     .description = "过三点构造圆",
     .mathematical_def = "C \\text{ 过 } A, B, C",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circle_by_diameter",
     .description = "以直径构造圆",
     .mathematical_def = "C \\text{ 以 } AB \\text{ 为直径}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "tangent_lines",
     .description = "从点向圆作切线",
     .mathematical_def = "L_1, L_2 \\text{ 切圆 } C \\text{ 于点 } P",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 2,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 交点构造 ========== */
    {.name = "line_intersection",
     .description = "求两直线交点",
     .mathematical_def = "P = l_1 \\cap l_2",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circle_line_intersection",
     .description = "求圆与直线的交点",
     .mathematical_def = "P_1, P_2 = C \\cap l",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 2,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circle_circle_intersection",
     .description = "求两圆交点",
     .mathematical_def = "P_1, P_2 = C_1 \\cap C_2",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 2,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 对称与反射 ========== */
    {.name = "reflection_point",
     .description = "求点关于直线的对称点",
     .mathematical_def = "P' \\text{ 满足 } PP' \\perp l \\text{ 且中点在 } l \\text{ 上}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_INVOLUTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "reflection_line",
     .description = "求直线关于另一直线的对称直线",
     .mathematical_def = "l' \\text{ 是 } l \\text{ 关于 } m \\text{ 的反射}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_INVOLUTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 特殊点构造 ========== */
    {.name = "foot_of_perpendicular",
     .description = "求点到直线的垂足",
     .mathematical_def = "F \\text{ 是 } P \\text{ 在 } l \\text{ 上的投影}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_IDEMPOTENT,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "harmonic_conjugate",
     .description = "构造调和共轭点",
     .mathematical_def = "(AB;CD) = -1",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_INVOLUTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 多边形构造 ========== */
    {.name = "equilateral_triangle",
     .description = "构造等边三角形",
     .mathematical_def = "\\triangle ABC \\text{ 等边}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 3,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "square",
     .description = "构造正方形",
     .mathematical_def = "\\square ABCD",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 2,
     .precondition_count = 1,
     .postcondition_count = 4,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "regular_polygon",
     .description = "构造正多边形",
     .mathematical_def = "P_n \\text{ 以 } AB \\text{ 为边}",
     .category = PRESET_CATEGORY_CONSTRUCTION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE,
     .complexity = COMPLEXITY_ON,
     .input_count = 3,
     .output_count = -1, /* 可变输出 */
     .precondition_count = 2,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 度量计算 ========== */
    {.name = "distance",
     .description = "计算两点间距离",
     .mathematical_def = "d = |AB| = \\sqrt{(x_B-x_A)^2 + (y_B-y_A)^2}",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_COMMUTATIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "distance_squared",
     .description = "计算两点间距离平方",
     .mathematical_def = "d^2 = |AB|^2",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_COMMUTATIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "angle_measure",
     .description = "计算角度大小",
     .mathematical_def = "\\theta = \\angle ABC",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "area_triangle",
     .description = "计算三角形面积",
     .mathematical_def = "S = \\frac{1}{2}|(B-A) \\times (C-A)|",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "area_polygon",
     .description = "计算多边形面积",
     .mathematical_def = "S = \\frac{1}{2}|\\sum_{i=1}^{n} (x_i y_{i+1} - x_{i+1} y_i)|",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_ON,
     .input_count = -1, /* 可变输入 */
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "circumference",
     .description = "计算圆周长",
     .mathematical_def = "C = 2\\pi r",
     .category = PRESET_CATEGORY_MEASUREMENT,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_O1,
     .input_count = 1,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 几何变换 ========== */
    {.name = "translation",
     .description = "平移变换",
     .mathematical_def = "P' = P + \\vec{v}",
     .category = PRESET_CATEGORY_TRANSFORMATION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_REVERSIBLE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "rotation",
     .description = "旋转变换",
     .mathematical_def = "P' = R_\\theta(O, P)",
     .category = PRESET_CATEGORY_TRANSFORMATION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_REVERSIBLE,
     .complexity = COMPLEXITY_O1,
     .input_count = 4,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "scaling",
     .description = "缩放变换",
     .mathematical_def = "P' = O + k(P - O)",
     .category = PRESET_CATEGORY_TRANSFORMATION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_REVERSIBLE,
     .complexity = COMPLEXITY_O1,
     .input_count = 4,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "homothety",
     .description = "位似变换",
     .mathematical_def = "H(O, k): P \\mapsto O + k\\vec{OP}",
     .category = PRESET_CATEGORY_TRANSFORMATION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_REVERSIBLE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "inversion",
     .description = "反演变换",
     .mathematical_def = "P' \\text{ 满足 } OP \\cdot OP' = r^2",
     .category = PRESET_CATEGORY_TRANSFORMATION,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_CONSTRUCTIVE |
                   PRESET_PROPERTY_INVOLUTIVE | PRESET_PROPERTY_REVERSIBLE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 2,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 代数运算 ========== */
    {.name = "vector_add",
     .description = "向量加法",
     .mathematical_def = "\\vec{c} = \\vec{a} + \\vec{b}",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_COMMUTATIVE |
                   PRESET_PROPERTY_ASSOCIATIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "vector_sub",
     .description = "向量减法",
     .mathematical_def = "\\vec{c} = \\vec{a} - \\vec{b}",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "vector_scale",
     .description = "向量数乘",
     .mathematical_def = "\\vec{b} = k\\vec{a}",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_LINEAR,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "vector_dot",
     .description = "向量点积",
     .mathematical_def = "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_COMMUTATIVE,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "vector_cross",
     .description = "向量叉积（二维）",
     .mathematical_def = "\\vec{a} \\times \\vec{b} = a_x b_y - a_y b_x",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 2,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "vector_normalize",
     .description = "向量单位化",
     .mathematical_def = "\\hat{a} = \\frac{\\vec{a}}{|\\vec{a}|}",
     .category = PRESET_CATEGORY_ALGEBRAIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC | PRESET_PROPERTY_CONTINUOUS | PRESET_PROPERTY_IDEMPOTENT,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 1,
     .postcondition_count = 2,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},

    /* ========== 逻辑推导 ========== */
    {.name = "collinearity_test",
     .description = "共线性检测",
     .mathematical_def =
         "\\text{det}\\begin{pmatrix} x_A & y_A & 1 \\\\ x_B & y_B & 1 \\\\ x_C & y_C & 1 \\end{pmatrix} = 0",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 3,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "concyclicity_test",
     .description = "共圆性检测",
     .mathematical_def = "\\text{四点共圆条件}",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 4,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "parallel_test",
     .description = "平行性检测",
     .mathematical_def = "l_1 \\parallel l_2 \\Leftrightarrow k_1 = k_2",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "perpendicular_test",
     .description = "垂直性检测",
     .mathematical_def = "l_1 \\perp l_2 \\Leftrightarrow k_1 k_2 = -1",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 3,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "point_in_circle_test",
     .description = "点在圆内检测",
     .mathematical_def = "|PC| < r",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
    {.name = "point_on_line_test",
     .description = "点在直线上检测",
     .mathematical_def = "P \\in l",
     .category = PRESET_CATEGORY_LOGIC,
     .properties = PRESET_PROPERTY_DETERMINISTIC,
     .complexity = COMPLEXITY_O1,
     .input_count = 2,
     .output_count = 1,
     .precondition_count = 0,
     .postcondition_count = 1,
     .related_count = 2,
     .version_major = 1,
     .version_minor = 0,
     .version_patch = 0},
};

/** 内置预设数量 */
const int g_builtin_count = sizeof(g_builtin_metadata) / sizeof(g_builtin_metadata[0]);
