# Batch-generate stub .c source files for CMake build
# Run: powershell -File gen_stubs.ps1

$base = Split-Path $PSScriptRoot -Parent
$files = @(
    'core/src/layer1_parser/dsl_compiler.c',
    'core/src/layer1_parser/formula_converter.c',
    'core/src/layer1_parser/lexer_shared.c',
    'core/src/layer1_parser/math_input.c',
    'core/src/layer2_resource/debug_trace.c',
    'core/src/layer2_resource/error_messages_cn.c',
    'core/src/layer2_resource/geometry_config.c',
    'core/src/layer2_resource/math_theory_guide_cn.c',
    'core/src/layer2_resource/preset_helper_cn.c',
    'core/src/layer2_resource/result_messages_cn.c',
    'core/src/layer3_geometry/algebraic_number.c',
    'core/src/layer3_geometry/euclidean_geometry.c',
    'core/src/layer3_geometry/fptaylor_eval.c',
    'core/src/layer3_geometry/ga_codegen.c',
    'core/src/layer3_geometry/ga_interface.c',
    'core/src/layer3_geometry/ga_multivector.c',
    'core/src/layer3_geometry/gappa_dsl.c',
    'core/src/layer3_geometry/gappa_propagate.c',
    'core/src/layer3_geometry/geo_aabb_tree.c',
    'core/src/layer3_geometry/geo_constraint_solver.c',
    'core/src/layer3_geometry/geo_dynamic.c',
    'core/src/layer3_geometry/geo_event_detect.c',
    'core/src/layer3_geometry/geo_halfedge_mesh.c',
    'core/src/layer3_geometry/geo_invariant_type.c',
    'core/src/layer3_geometry/geo_predicate.c',
    'core/src/layer3_geometry/geo_spec.c',
    'core/src/layer3_geometry/geo_topology.c',
    'core/src/layer3_geometry/geo_utils.c',
    'core/src/layer3_geometry/geometry_compress.c',
    'core/src/layer3_geometry/geometry_transform.c',
    'core/src/layer3_geometry/herbie_eval.c',
    'core/src/layer3_geometry/high_dim.c',
    'core/src/layer3_geometry/interactive_geo.c',
    'core/src/layer3_geometry/interval_arithmetic.c',
    'core/src/layer3_geometry/mpz_poly_resultant.c',
    'core/src/layer3_geometry/simd_ops.c',
    'core/src/layer3_geometry/sparse_linear_algebra.c',
    'core/src/layer3_geometry/thread_pool.c',
    'core/src/layer4_reasoning/algebra_mode.c',
    'core/src/layer4_reasoning/approx_counter.c',
    'core/src/layer4_reasoning/autodiff.c',
    'core/src/layer4_reasoning/axiom/axiom_grade.c',
    'core/src/layer4_reasoning/axiom/axiom_pkg.c',
    'core/src/layer4_reasoning/circuit_breaker.c',
    'core/src/layer4_reasoning/ecosystem.c',
    'core/src/layer4_reasoning/engine_scheduler.c',
    'core/src/layer4_reasoning/exact_arithmetic.c',
    'core/src/layer4_reasoning/expr_canon.c',
    'core/src/layer4_reasoning/func_block/func_block_compose.c',
    'core/src/layer4_reasoning/func_block/func_block_determinism.c',
    'core/src/layer4_reasoning/func_block/func_block_instantiate.c',
    'core/src/layer4_reasoning/func_block/func_block_preset.c',
    'core/src/layer4_reasoning/func_block/func_block_preset_ops.c',
    'core/src/layer4_reasoning/func_block/func_block_registry.c',
    'core/src/layer4_reasoning/func_block/func_block_selector.c',
    'core/src/layer4_reasoning/func_block/func_block_serialize.c',
    'core/src/layer4_reasoning/func_block/func_block_utils.c',
    'core/src/layer4_reasoning/func_block/preset_abstract_algebra.c',
    'core/src/layer4_reasoning/func_block/preset_basic_math.c',
    'core/src/layer4_reasoning/func_block/preset_calculus.c',
    'core/src/layer4_reasoning/func_block/preset_manager.c',
    'core/src/layer4_reasoning/gc_language.c',
    'core/src/layer4_reasoning/groebner_engine.c',
    'core/src/layer4_reasoning/logic_check.c',
    'core/src/layer4_reasoning/math_protocol.c',
    'core/src/layer4_reasoning/meta_proof.c',
    'core/src/layer4_reasoning/mini_kernel.c',
    'core/src/layer4_reasoning/modal_operators.c',
    'core/src/layer4_reasoning/module.c',
    'core/src/layer4_reasoning/normalization.c',
    'core/src/layer4_reasoning/nt_number_theory.c',
    'core/src/layer4_reasoning/nt_polynomial.c',
    'core/src/layer4_reasoning/ode_solver.c',
    'core/src/layer4_reasoning/preset/preset_advanced_geometry.c',
    'core/src/layer4_reasoning/preset/preset_algebraic.c',
    'core/src/layer4_reasoning/preset/preset_algebraic_geometry.c',
    'core/src/layer4_reasoning/preset/preset_algebraic_topology.c',
    'core/src/layer4_reasoning/preset/preset_algebraic_topology_adv.c',
    'core/src/layer4_reasoning/preset/preset_analysis.c',
    'core/src/layer4_reasoning/preset/preset_arithmetic_geometry.c',
    'core/src/layer4_reasoning/preset/preset_basic_geometry.c',
    'core/src/layer4_reasoning/preset/preset_category_theory.c',
    'core/src/layer4_reasoning/preset/preset_category_theory_adv.c',
    'core/src/layer4_reasoning/preset/preset_coding_theory.c',
    'core/src/layer4_reasoning/preset/preset_combinatorics.c',
    'core/src/layer4_reasoning/preset/preset_complex_analysis.c',
    'core/src/layer4_reasoning/preset/preset_difference_equations.c',
    'core/src/layer4_reasoning/preset/preset_differential_equations.c',
    'core/src/layer4_reasoning/preset/preset_differential_geometry.c',
    'core/src/layer4_reasoning/preset/preset_differential_geometry_adv.c',
    'core/src/layer4_reasoning/preset/preset_dynamical_systems.c',
    'core/src/layer4_reasoning/preset/preset_field_theory.c',
    'core/src/layer4_reasoning/preset/preset_functional_analysis.c',
    'core/src/layer4_reasoning/preset/preset_functional_analysis_adv.c',
    'core/src/layer4_reasoning/preset/preset_game_theory.c',
    'core/src/layer4_reasoning/preset/preset_geometry_3d.c',
    'core/src/layer4_reasoning/preset/preset_graph_theory.c',
    'core/src/layer4_reasoning/preset/preset_group_theory.c',
    'core/src/layer4_reasoning/preset/preset_homological_algebra.c',
    'core/src/layer4_reasoning/preset/preset_information_theory.c',
    'core/src/layer4_reasoning/preset/preset_integral_transforms.c',
    'core/src/layer4_reasoning/preset/preset_lattice_theory.c',
    'core/src/layer4_reasoning/preset/preset_lie_theory_advanced.c',
    'core/src/layer4_reasoning/preset/preset_linear_algebra.c',
    'core/src/layer4_reasoning/preset/preset_logic_advanced.c',
    'core/src/layer4_reasoning/preset/preset_math_logic.c',
    'core/src/layer4_reasoning/preset/preset_mathematical_logic.c',
    'core/src/layer4_reasoning/preset/preset_mathematical_physics.c',
    'core/src/layer4_reasoning/preset/preset_matrix.c',
    'core/src/layer4_reasoning/preset/preset_measure_theory.c',
    'core/src/layer4_reasoning/preset/preset_number_theory.c',
    'core/src/layer4_reasoning/preset/preset_numerical.c',
    'core/src/layer4_reasoning/preset/preset_numerical_analysis.c',
    'core/src/layer4_reasoning/preset/preset_optimization.c',
    'core/src/layer4_reasoning/preset/preset_order_theory.c',
    'core/src/layer4_reasoning/preset/preset_polynomial.c',
    'core/src/layer4_reasoning/preset/preset_probability.c',
    'core/src/layer4_reasoning/preset/preset_probability_statistics.c',
    'core/src/layer4_reasoning/preset/preset_representation_theory.c',
    'core/src/layer4_reasoning/preset/preset_set_theory.c',
    'core/src/layer4_reasoning/preset/preset_special_functions.c',
    'core/src/layer4_reasoning/preset/preset_statistics.c',
    'core/src/layer4_reasoning/preset/preset_stochastic_processes.c',
    'core/src/layer4_reasoning/preset/preset_topology.c',
    'core/src/layer4_reasoning/preset/preset_transformations.c',
    'core/src/layer4_reasoning/preset/preset_trigonometry.c',
    'core/src/layer4_reasoning/proof_contradiction.c',
    'core/src/layer4_reasoning/proof_optimize.c',
    'core/src/layer4_reasoning/proof_priority.c',
    'core/src/layer4_reasoning/proof_rule_engine.c',
    'core/src/layer4_reasoning/proof_session.c',
    'core/src/layer4_reasoning/proof_trace.c',
    'core/src/layer4_reasoning/proof_version.c',
    'core/src/layer4_reasoning/prop_verifier.c',
    'core/src/layer4_reasoning/rational.c',
    'core/src/layer4_reasoning/recursion.c',
    'core/src/layer4_reasoning/rewrite.c',
    'core/src/layer4_reasoning/rewrite_strategy.c',
    'core/src/layer4_reasoning/smt_bitvector.c',
    'core/src/layer4_reasoning/smt_theory_combiner.c',
    'core/src/layer4_reasoning/smt_trigger_engine.c',
    'core/src/layer4_reasoning/sym_expr.c',
    'core/src/layer4_reasoning/three_valued_logic.c',
    'core/src/layer4_reasoning/unify.c',
    'core/src/layer5_output/geo_visual_complete.c',
    'core/src/layer5_output/proof_export_enhanced.c',
    'core/src/layer5_output/proof_widget.c',
    'core/src/layer5_output/tikz_export.c'
)

$count = 0
foreach ($f in $files) {
    $full = Join-Path $base $f
    $dir = Split-Path $full -Parent
    if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    if (Test-Path $full) { continue }
    $name = [IO.Path]::GetFileNameWithoutExtension($f)
    $content = @"
/* Stub for ${name} — TODO: implement */
#include "lv/lv.h"
"@
    [IO.File]::WriteAllText($full, $content, [Text.Encoding]::UTF8)
    $count++
}
Write-Host "Created $count new stub files (skipped $($files.Count - $count) existing)"
