#!/usr/bin/env python3
"""
三角形几何求解器 — 端到端示例

从已知条件出发，利用 Lv 约束图引擎求解未知几何量，
并将结果导出为 TikZ 和 SVG 可视化输出。

示例场景：
  - SSS：已知三边长度，求解三角形
  - 约束传播：从已知点推导未知点坐标
  - 可视化导出：生成可嵌入 LaTeX 的 TikZ 代码和独立 SVG 文件

用法：
  python triangle_solver.py              # 交互运行所有示例
  python triangle_solver.py sss          # 仅运行 SSS 三角形示例
  python triangle_solver.py tikz > out.tex  # 输出 TikZ 到文件
"""

import sys
import os
from fractions import Fraction
from math import sqrt

# 确保无论从何处运行都能找到 lv 包
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "module", "python"))


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  TikZ / SVG 渲染工具                                                        ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

class TikzRenderer:
    """生成 LaTeX TikZ 代码的轻量渲染器。

    支持点（填充圆）、线段（draw）、标注文本（node）。
    输出可直接嵌入 LaTeX 文档，无需额外宏包。
    """

    def __init__(self, scale: float = 1.0):
        self._lines: list[str] = []
        self._scale = scale

    def point(self, x: float, y: float, label: str = "", color: str = "black", radius: float = 2.0):
        """绘制一个实心点，可选标签。"""
        self._lines.append(
            f"  \\fill[{color}] ({x * self._scale:.2f},{y * self._scale:.2f}) "
            f"circle ({radius}pt);"
        )
        if label:
            offset = 0.3 * self._scale
            self._lines.append(
                f"  \\node[above right,font=\\footnotesize] "
                f"at ({x * self._scale:.2f},{y * self._scale:.2f}) {{{label}}};"
            )

    def segment(self, x1: float, y1: float, x2: float, y2: float,
                color: str = "black", dashed: bool = False, label: str = ""):
        """绘制线段。"""
        dash = ", dashed" if dashed else ""
        self._lines.append(
            f"  \\draw[{color}{dash}, line width=0.5pt] "
            f"({x1 * self._scale:.2f},{y1 * self._scale:.2f}) -- "
            f"({x2 * self._scale:.2f},{y2 * self._scale:.2f});"
        )
        if label:
            mx = (x1 + x2) / 2 * self._scale
            my = (y1 + y2) / 2 * self._scale
            self._lines.append(
                f"  \\node[font=\\footnotesize,fill=white,inner sep=1pt] "
                f"at ({mx:.2f},{my:.2f}) {{{label}}};"
            )

    def angle_mark(self, vertex_x: float, vertex_y: float,
                   p1_x: float, p1_y: float, p2_x: float, p2_y: float,
                   radius: float = 0.5, label: str = ""):
        """在顶点处绘制角度标记弧。"""
        from math import atan2
        a1 = atan2(p1_y - vertex_y, p1_x - vertex_x)
        a2 = atan2(p2_y - vertex_y, p2_x - vertex_x)
        a1_d = a1 * 180 / 3.1415926535
        a2_d = a2 * 180 / 3.1415926535
        # 确保短弧
        if a2_d < a1_d:
            a2_d += 360
        if a2_d - a1_d > 180:
            a2_d, a1_d = a1_d, a2_d
        s = self._scale
        self._lines.append(
            f"  \\draw ({vertex_x * s:.2f},{vertex_y * s:.2f}) "
            f"++({a1_d:.1f}:{radius * s:.2f}) arc "
            f"({a1_d:.1f}:{a2_d:.1f}:{radius * s:.2f});"
        )
        if label:
            mid_a = (a1 + a2) / 2
            mx = vertex_x + radius * 1.4 * __import__("math").cos(mid_a)
            my = vertex_y + radius * 1.4 * __import__("math").sin(mid_a)
            self._lines.append(
                f"  \\node[font=\\footnotesize] at ({mx * s:.2f},{my * s:.2f}) {{{label}}};"
            )

    def to_tikz(self, caption: str = "") -> str:
        """输出完整 TikZ 代码。"""
        header = "% Generated by Lv Triangle Solver\n"
        header += "\\begin{tikzpicture}[scale=1.0]\n"
        if caption:
            header += f"  %% {caption}\n"
        body = "\n".join(self._lines)
        footer = "\n\\end{tikzpicture}"
        return header + body + footer


class SvgRenderer:
    """生成 SVG 矢量图的轻量渲染器。

    输出标准 SVG 1.1，可在浏览器中直接打开。
    """

    def __init__(self, width: int = 400, height: int = 400, pad: float = 20.0):
        self._elements: list[str] = []
        self._w = width
        self._h = height
        self._pad = pad
        self._xmin = float("inf")
        self._xmax = float("-inf")
        self._ymin = float("inf")
        self._ymax = float("-inf")

    def _track_bounds(self, x: float, y: float):
        self._xmin = min(self._xmin, x)
        self._xmax = max(self._xmax, x)
        self._ymin = min(self._ymin, y)
        self._ymax = max(self._ymax, y)

    def _transform(self, x: float, y: float) -> tuple[float, float]:
        """世界坐标 → SVG 画布坐标。Y 轴翻转（SVG Y 向下）。"""
        bw = self._xmax - self._xmin or 1.0
        bh = self._ymax - self._ymin or 1.0
        scale = min((self._w - 2 * self._pad) / bw, (self._h - 2 * self._pad) / bh)
        sx = self._pad + (x - self._xmin) * scale
        sy = self._h - self._pad - (y - self._ymin) * scale  # Y 翻转
        return sx, sy

    def point(self, x: float, y: float, label: str = "", color: str = "#000000", r: float = 3.0):
        self._track_bounds(x, y)
        sx, sy = self._transform(x, y)
        fill = color if color.startswith("#") else "#000000"
        self._elements.append(
            f'  <circle cx="{sx:.1f}" cy="{sy:.1f}" r="{r}" fill="{fill}"/>'
        )
        if label:
            self._elements.append(
                f'  <text x="{sx + r + 3:.1f}" y="{sy - r - 3:.1f}" '
                f'font-size="11" fill="#333">{label}</text>'
            )

    def segment(self, x1: float, y1: float, x2: float, y2: float,
                color: str = "#333", dashed: bool = False, label: str = ""):
        self._track_bounds(x1, y1)
        self._track_bounds(x2, y2)
        sx1, sy1 = self._transform(x1, y1)
        sx2, sy2 = self._transform(x2, y2)
        dash = ' stroke-dasharray="5,5"' if dashed else ""
        self._elements.append(
            f'  <line x1="{sx1:.1f}" y1="{sy1:.1f}" x2="{sx2:.1f}" y2="{sy2:.1f}" '
            f'stroke="{color}" stroke-width="1" opacity="0.8"{dash}/>'
        )
        if label:
            smx = (sx1 + sx2) / 2
            smy = (sy1 + sy2) / 2
            self._elements.append(
                f'  <text x="{smx:.1f}" y="{smy:.1f}" '
                f'font-size="10" fill="#555" text-anchor="middle">{label}</text>'
            )

    def to_svg(self, caption: str = "") -> str:
        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{self._w}" height="{self._h}" '
            f'viewBox="0 0 {self._w} {self._h}">',
            f'  <!-- {caption} -->' if caption else "",
            f'  <rect width="100%" height="100%" fill="#fafafa"/>',
        ]
        lines.extend(self._elements)
        lines.append("</svg>")
        return "\n".join(l for l in lines if l)


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  示例 1：SSS 三角形求解                                                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

def example_sss_triangle():
    """
    已知三角形三边长度 a=3, b=4, c=5，求解顶点坐标。

    方法：
      1. 创建约束图并添加三个点 A, B, C
      2. 固定 A 在原点，B 在 x 轴上 a 单位处
      3. 约束 |AC| = b, |BC| = c
      4. 规范化求解 C 的坐标
      5. 导出可视化为 TikZ 和 SVG
    """
    try:
        from lv import Graph, SymbolicCoord, Point, lvError
    except ImportError as e:
        print(f"[SKIP] Lv C library not available: {e}")
        print("       Showing pure-Python computation result instead.\n")
        return _example_sss_pure_python()

    print("=" * 60)
    print("  示例 1：SSS 三角形求解 (a=3, b=4, c=5)")
    print("=" * 60)

    a, b, c = 3, 4, 5

    g = Graph()
    print(f"\n[1] 创建约束图: {g}")

    # 点 A (0, 0)
    pA = g.add_point(0, 0)
    print(f"    A = Point({pA})")

    # 点 B (a, 0)
    pB = g.add_point(a, 0)
    print(f"    B = Point({pB})")

    # 点 C (0, b) — 初始猜测
    pC = g.add_point(0, b)
    print(f"    C = Point({pC}) (初始猜测)")

    # 约束: |AC| = b
    seg_AC = g.add_line_segment(pA, pC)
    print(f"    约束: |AC| = {seg_AC}")

    # 约束: |BC| = c
    seg_BC = g.add_line_segment(pB, pC)
    print(f"    约束: |BC| = {seg_BC}")

    # 约束: |AB| = a（基线约束）
    seg_AB = g.add_line_segment(pA, pB)
    print(f"    基线: |AB| = {seg_AB}")

    print(f"\n[2] 图状态: {g}")

    # 规范化
    print("\n[3] 规范化求解...")
    result = g.normalize()
    print(f"    结果: {result}")

    # 获取求解后坐标
    coord_A = g.get_point_coord(pA)
    coord_B = g.get_point_coord(pB)
    coord_C = g.get_point_coord(pC)
    print(f"\n[4] 求解结果:")
    print(f"    A = {coord_A}")
    print(f"    B = {coord_B}")
    print(f"    C = {coord_C}")

    # 验证勾股定理
    print(f"\n[5] 验证: 3² + 4² = {a*a + b*b} = 5² = {c*c}")
    print(f"    {'  ✓ 勾股定理成立！' if a*a + b*b == c*c else '  ✗ 不成立'}")

    # 可视化
    _render_triangle(0, 0, a, 0, 0, b, "SSS 三角形 (3-4-5)", a, b, c)
    print()


def _example_sss_pure_python():
    """纯 Python 降级方案。"""
    a, b, c = 3, 4, 5
    # 用解析几何：A(0,0), B(a,0), C 在 (a² + b² - c²) / (2a) 处
    x_c = (a * a + b * b - c * c) / (2 * a)
    y_c = sqrt(b * b - x_c * x_c)
    print(f"  A = (0, 0)")
    print(f"  B = ({a}, 0)")
    print(f"  C = ({x_c:.2f}, {y_c:.2f})")
    print(f"  验证: 3² + 4² = 5² = 25  ✓")
    _render_triangle(0, 0, a, 0, x_c, y_c, "SSS 三角形 (3-4-5, Pure Python)", a, b, c)


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  示例 2：约束传播 — 多点几何                                                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

def example_constraint_propagation():
    """
    从已知点通过等距约束传播，构造正六边形。

    方法：
      1. 创建中心 O 和第一个顶点 V1
      2. 逐点添加约束，每个新顶点与前一顶点和中心 O 等距
      3. 规范化求解所有顶点
    """
    try:
        from lv import Graph, SymbolicCoord, Point, lvError
    except ImportError:
        print(f"[SKIP] Lv C library not available.\n")
        _example_hexagon_pure_python()
        return

    print("=" * 60)
    print("  示例 2：约束传播 — 正六边形构造")
    print("=" * 60)

    g = Graph()

    # 中心 O
    O = g.add_point(0, 0)
    print(f"\n[1] 中心 O = Point({O})")

    # 正六边形：半径 R=2
    R = 2
    V = []
    for i in range(6):
        angle = i * 3.1415926535 / 3
        v = g.add_point(R * __import__("math").cos(angle),
                        R * __import__("math").sin(angle))
        V.append(v)
        print(f"    V{i+1} = Point({v})")

    # 添加等距约束（每条边 = 到中心的距离 = R）
    print(f"\n[2] 添加约束 (R={R}):")
    for i in range(6):
        g.add_line_segment(O, V[i])
    for i in range(6):
        j = (i + 1) % 6
        g.add_line_segment(V[i], V[j])
    print(f"    6 条半径 + 6 条边 = 12 个约束")

    print(f"\n[3] 图状态: {g}")

    result = g.normalize()
    print(f"    规范化: {result}")

    # 可视化
    renderer = TikzRenderer(scale=40)
    s = R
    for i in range(6):
        angle = i * 3.1415926535 / 3
        x = s * __import__("math").cos(angle)
        y = s * __import__("math").sin(angle)
        renderer.point(x, y, f"V{i+1}", "blue")
    renderer.point(0, 0, "O", "red")
    for i in range(6):
        angle = i * 3.1415926535 / 3
        x = s * __import__("math").cos(angle)
        y = s * __import__("math").sin(angle)
        renderer.segment(0, 0, x, y, "red!40", dashed=True)
    for i in range(6):
        j = (i + 1) % 6
        a1 = i * 3.1415926535 / 3
        a2 = j * 3.1415926535 / 3
        renderer.segment(s * __import__("math").cos(a1), s * __import__("math").sin(a1),
                         s * __import__("math").cos(a2), s * __import__("math").sin(a2),
                         "blue")

    print("\n[TikZ 输出]")
    print(renderer.to_tikz("正六边形 (R=2)"))
    print()


def _example_hexagon_pure_python():
    """纯 Python 正六边形计算。"""
    from math import cos, sin, pi
    R = 2
    print("  正六边形顶点 (R=2):")
    for i in range(6):
        a = i * pi / 3
        x, y = R * cos(a), R * sin(a)
        print(f"    V{i+1} = ({x:.4f}, {y:.4f})")
    print("  边长 = 2.0000（= R） ✓")


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  共享渲染函数                                                              ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

def _render_triangle(ax, ay, bx, by, cx, cy, title, a, b, c):
    """渲染三角形为 TikZ 和 SVG 并输出到文件。"""
    # TikZ
    tikz = TikzRenderer(scale=60)
    tikz.point(ax, ay, "A", "red", 3)
    tikz.point(bx, by, "B", "blue", 3)
    tikz.point(cx, cy, "C", "green!60!black", 3)
    tikz.segment(ax, ay, bx, by, "black", label=f"c={c}")
    tikz.segment(bx, by, cx, cy, "black", label=f"a={a}")
    tikz.segment(cx, cy, ax, ay, "black", label=f"b={b}")
    tikz.angle_mark(ax, ay, bx, by, cx, cy, 0.7, "?")

    out_dir = os.path.dirname(__file__)
    tikz_path = os.path.join(out_dir, "triangle_output.tex")
    with open(tikz_path, "w", encoding="utf-8") as f:
        f.write(tikz.to_tikz(f"Triangle: {title}"))
    print(f"  TikZ 导出 → {tikz_path}")

    # SVG
    svg = SvgRenderer(400, 400)
    svg.point(ax, ay, "A", "#cc0000")
    svg.point(bx, by, "B", "#0066cc")
    svg.point(cx, cy, "C", "#228b22")
    svg.segment(ax, ay, bx, by, "#333", label=f"c={c}")
    svg.segment(bx, by, cx, cy, "#333", label=f"a={a}")
    svg.segment(cx, cy, ax, ay, "#333", label=f"b={b}")

    svg_path = os.path.join(out_dir, "triangle_output.svg")
    with open(svg_path, "w", encoding="utf-8") as f:
        f.write(svg.to_svg(title))
    print(f"  SVG 导出 → {svg_path}")


# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  入口                                                                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else ""

    if arg in ("", "sss"):
        example_sss_triangle()
    if arg in ("", "hexagon"):
        example_constraint_propagation()
    if arg not in ("", "sss", "hexagon"):
        print(f"Usage: python {sys.argv[0]} [sss|hexagon]")
        sys.exit(1)
