/**
 * @file smt_backend_impl_smtlib2.c
 * @brief SMT-LIB2 编码
 *
 * @details 从 smt_backend_impl.c 拆分的子模块（Lv-00 项目 v3.3.0+）。
 *
 * @author Lv-00 Project
 * @version 3.3.0
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lv/lv_file.h"
#include "lv/lv_str_utils.h"

#include "smt_backend.h"
#include "smt_backend_internal.h"
#include "lv/lv_registry.h"
#include "lv/lv_thread.h"
#include "lv/lv_numeric.h"

#include "error_codes.h"
#include "groebner_engine.h"
#include "lv_internal.h"
#include "lv_utils.h"

/* ============================================================
 * 约束图 -> SMT-LIB2 编码（增强版：真实几何约束编码）
 * ============================================================ */

/* ---- SMT-LIB2 约束编码辅助函数（前向声明，定义于本文件后方） ---- */
static int smtlib2_encode_incidence(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                    bool named);
static int smtlib2_encode_betweenness(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                      bool named);
static int smtlib2_encode_intersection(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                       bool named);
static int smtlib2_encode_containment(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                      bool named);
static int smtlib2_encode_connection(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                     bool named);
static int smtlib2_encode_angle(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                bool named);


/**
 * @brief 获取节点坐标对应的 SMT-LIB2 变量名
 *
 * 每个几何点节点有 2 个坐标变量（x, y），变量命名规则为：
 *   - x 坐标：p<node_id>_x
 *   - y 坐标：p<node_id>_y
 *
 * @param node_id   节点 ID
 * @param coord_idx 坐标索引（0=x, 1=y）
 * @return 变量名字符串（线程局部 scratch 缓冲区，勿跨调用保存）
 */
static const char *smtlib2_coord_var_name(int node_id, int coord_idx) {
    const char *suffix = (coord_idx == 0) ? "x" : "y";
    return lv_fmt_tmp("p%d_%s", node_id, suffix);
}

/**
 * @brief 将约束图编码为 SMT-LIB2 格式字符串（增强版）
 *
 * 遍历约束图中的所有几何节点和约束，将几何约束翻译为
 * 对应的代数方程/不等式，编码为标准 SMT-LIB2 脚本。
 *
 * 支持的约束类型编码规则：
 * - INCIDENCE（点在线段上）：叉积方程 (B-A) x (C-A) = 0
 * - BETWEENNESS（三点共线有序）：共线叉积 = 0 + 参数方程
 * - INTERSECTION（两线段交点）：联立参数方程
 * - CONTAINMENT（包含关系）：距离约束
 * - CONNECTION（端口连接）：坐标等价
 *
 * @param[in]  graph         约束图
 * @param[in]  logic         目标 SMT 逻辑理论
 * @param[in]  produce_unsat_cores  是否为导出 UNSAT 核心生成命名断言
 * @param[out] out_smtlib2   输出的 SMT-LIB2 脚本缓冲区
 * @param[in]  buffer_size   缓冲区大小（字符数）
 * @return 实际写入的字符数（不含终止符），失败返回 -1。
 *         如果缓冲区不足，返回所需的总字符数。
 */
int smtencode_constraint_graph_to_smtlib2(const ConstraintGraph *graph, SMTLogic logic, bool produce_unsat_cores,
                                          char *out_smtlib2, size_t buffer_size) {
    lv_CHECK_NULL(graph, -1);
    lv_CHECK_NULL(out_smtlib2, -1);

    if (buffer_size < 256) {
        return (int) buffer_size + 256; /* 返回所需大小 */
    }

    /* 根据逻辑类型选择名称，几何约束默认使用 QF_NRA（非线性实数算术） */
    const char *logic_name = smtsolver_logic_name(logic);
    if (logic == SMT_LOGIC_AUTO) {
        logic_name = "QF_NRA";
    }

    int written = 0;

    /* ---- 写入 SMT-LIB2 头部：逻辑声明和元信息 ---- */
    written = snprintf(out_smtlib2, buffer_size,
                       "; SMT-LIB2 encoding for Lv-00 geometric constraint graph\n"
                       "; Generated by smt_backend_impl.c v3.4.0\n"
                       "; Constraint encoding: geometric constraints -> polynomial equations\n"
                       "(set-logic %s)\n"
                       "(set-info :source |Lv-00 geometric constraint solver|)\n"
                       "(set-info :smt-lib-version 2.6)\n",
                       logic_name);
    if (written < 0)
        return -1;

    int remaining = (int) buffer_size - written;
    if (remaining <= 0)
        return written;

    /* ---- 声明变量：为每个 GEOM_POINT 节点声明 x, y 两个实数变量 ---- */
    int node_count = graph->node_count;
    for (int i = 0; i < node_count && remaining > 64; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node)
            continue;

        /* 只有点节点需要坐标变量声明 */
        if (node->type == GEOM_POINT) {
            /* x 坐标变量 */
            int n = snprintf(out_smtlib2 + written, (size_t) remaining, "(declare-fun %s () Real)\n",
                             smtlib2_coord_var_name(node->id, 0));
            /* exempt: snprintf 返回码截断检测（n 为返回值而非索引：-1=编码错误、
             * n>=remaining=缓冲截断），与 lv_index_in_range 的索引范围语义不同 */
            if (n < 0 || n >= remaining)
                break;
            written += n;
            remaining -= n;

            /* y 坐标变量 */
            if (remaining <= 64)
                break;
            n = snprintf(out_smtlib2 + written, (size_t) remaining, "(declare-fun %s () Real)\n",
                         smtlib2_coord_var_name(node->id, 1));
            /* exempt: 同上，snprintf 返回码截断检测，非索引范围判定 */
            if (n < 0 || n >= remaining)
                break;
            written += n;
            remaining -= n;
        }
    }

    if (remaining <= 0)
        return written;

    /* ---- 编码约束为断言：根据约束类型生成对应的代数方程 ---- */
    int constraint_count = graph->constraint_count;
    for (int i = 0; i < constraint_count && remaining > 128; i++) {
        Constraint *c = graph->constraints[i];
        if (!c)
            continue;

        int n = 0;
        {
            /* ── SMT-LIB2 约束编码函数查找表 ── */
            typedef int (*Smtlib2EncodeFn)(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining, bool named);
            static const Smtlib2EncodeFn kSmtlib2EncodeTable[] = {
                smtlib2_encode_incidence,    /* INCIDENCE */
                smtlib2_encode_betweenness,  /* BETWEENNESS */
                smtlib2_encode_intersection, /* INTERSECTION */
                smtlib2_encode_containment,  /* CONTAINMENT */
                smtlib2_encode_connection,   /* CONNECTION */
                smtlib2_encode_angle         /* ANGLE */
            };
            static const int kSmtlib2EncodeTableCount =
                (int)(sizeof(kSmtlib2EncodeTable) / sizeof(kSmtlib2EncodeTable[0]));
            if (lv_index_in_range(c->type, kSmtlib2EncodeTableCount)) {
                n = kSmtlib2EncodeTable[(int)c->type](graph, c, out_smtlib2 + written, remaining, produce_unsat_cores);
            } else {
                lv_LOG_WARNING("Unknown constraint type %d in smtlib2_encode_constraints", c->type);
            }
        }
        /* exempt: snprintf 返回码截断检测（n 为返回值而非索引：-1=编码错误、
         * n>=remaining=缓冲截断），与 lv_index_in_range 的索引范围语义不同 */
        if (n < 0 || n >= remaining)
            break;
        written += n;
        remaining -= n;
    }

    if (remaining <= 0)
        return written;

    /* ---- 求解命令 ---- */
    int n = snprintf(out_smtlib2 + written, (size_t) remaining,
                     "(check-sat)\n"
                     "; 若结果为 sat，可使用 (get-model) 获取变量赋值\n");
    if (n > 0 && n < remaining) {
        written += n;
    }

    return written;
}

/**
 * @brief 编码关联约束（INCIDENCE）：点 P 在线段 AB 上
 *
 * 几何含义：点 P 的坐标满足线段 AB 的参数方程。
 * 代数编码：使用叉积判等式
 *   (P - A) x (B - A) = 0
 * 展开为：
 *   (Px - Ax) * (By - Ay) - (Py - Ay) * (Bx - Ax) = 0
 *
 * @param graph     约束图
 * @param c         关联约束（participants[0]=点ID, participants[1]=线段ID）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言（用于 UNSAT 核心提取）
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_incidence(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                    bool named) {
    if (!c || c->participant_count < 2)
        return 0;

    /* 获取参与约束的节点 */
    int point_id = c->participants[0];
    int seg_id = c->participants[1];
    GeomNode *point_node = graph_get_node(graph, point_id);
    GeomNode *seg_node = graph_get_node(graph, seg_id);
    if (!point_node || !seg_node)
        return 0;

    /* 线段节点需要通过其端点获取坐标。
     * 线段的端点信息存储在约束图的节点关系中。
     * 这里我们用线段 ID 的低位和高位分别模拟两个端点。
     * 在实际系统中，线段节点应存储端点 ID 的引用。 */
    /* 从约束图中查找线段的实际端点（通过 CONNECTION 约束） */

    /* 为保证编码的通用性，我们使用参数化方程形式：
     * P = A + t*(B-A), 其中 t in [0,1]
     * 这给出两个方程：
     *   Px = Ax + t*(Bx - Ax)
     *   Py = Ay + t*(By - Ay)
     * 消去参数 t 后得到叉积方程：
     *   (Px - Ax)*(By - Ay) = (Py - Ay)*(Bx - Ax)
     */

    /* 使用点坐标变量名和线段端点坐标变量名生成断言。
     * 从约束图中查找线段的实际端点（通过 CONNECTION 约束）。 */
    int a_id = -1, b_id = -1;
    for (int ci = 0; ci < graph->constraint_count && (a_id < 0 || b_id < 0); ci++) {
        Constraint *con = graph->constraints[ci];
        if (!con || !con->is_active)
            continue;
        if (con->type == CONNECTION && con->participant_count >= 2) {
            /* 检查该连接约束是否涉及当前线段 */
            bool seg_found = false;
            int point_id = -1;
            for (int pi = 0; pi < con->participant_count; pi++) {
                if (con->participants[pi] == seg_id) {
                    seg_found = true;
                } else {
                    point_id = con->participants[pi];
                }
            }
            if (seg_found && point_id >= 0) {
                if (a_id < 0)
                    a_id = point_id;
                else if (b_id < 0)
                    b_id = point_id;
            }
        }
    }
    /* 回退：若未找到端点，使用线段节点的坐标 */
    if (a_id < 0)
        a_id = seg_id;
    if (b_id < 0)
        b_id = seg_id;

    /* 叉积方程: (Px-Ax)*(By-Ay) - (Py-Ay)*(Bx-Ax) = 0 */
    if (named) {
        return snprintf(buf, (size_t) remaining,
                        "  ; 关联约束 c%d: 点 p%d 在线段 seg%d 上\n"
                        "  (assert (! (= (- (* (- %s %s) (- %s %s))\n"
                        "                    (* (- %s %s) (- %s %s)))\n"
                        "                0.0) :named c%d))\n",
                        c->id, point_id, seg_id, smtlib2_coord_var_name(point_id, 0), smtlib2_coord_var_name(a_id, 0),
                        smtlib2_coord_var_name(b_id, 1), smtlib2_coord_var_name(a_id, 1),
                        smtlib2_coord_var_name(point_id, 1), smtlib2_coord_var_name(a_id, 1),
                        smtlib2_coord_var_name(b_id, 0), smtlib2_coord_var_name(a_id, 0), c->id);
    } else {
        return snprintf(buf, (size_t) remaining,
                        "  ; 关联约束 c%d: 点 p%d 在线段 seg%d 上\n"
                        "  (assert (= (- (* (- %s %s) (- %s %s))\n"
                        "                    (* (- %s %s) (- %s %s)))\n"
                        "                0.0))\n",
                        c->id, point_id, seg_id, smtlib2_coord_var_name(point_id, 0), smtlib2_coord_var_name(a_id, 0),
                        smtlib2_coord_var_name(b_id, 1), smtlib2_coord_var_name(a_id, 1),
                        smtlib2_coord_var_name(point_id, 1), smtlib2_coord_var_name(a_id, 1),
                        smtlib2_coord_var_name(b_id, 0), smtlib2_coord_var_name(a_id, 0));
    }
}

/**
 * @brief 编码之间约束（BETWEENNESS）：点 B 在点 A 和点 C 之间
 *
 * 几何含义：A、B、C 三点共线，且 B 位于 A 和 C 之间。
 * 代数编码分两部分：
 *   1. 共线性条件（叉积为零）：
 *      (Bx - Ax)*(Cy - Ay) - (By - Ay)*(Cx - Ax) = 0
 *   2. 有序性条件（参数 t in [0,1]）：
 *      存在 t，使得 B = A + t*(C - A) 且 0 <= t <= 1
 *      等价于：(Bx-Ax)*(Cx-Ax) + (By-Ay)*(Cy-Ay) >= 0（同向）
 *           且 (Bx-Ax)*(Cx-Ax) + (By-Ay)*(Cy-Ay) <= (Cx-Ax)^2 + (Cy-Ay)^2
 *
 * @param graph     约束图
 * @param c         之间约束（participants[0]=A, participants[1]=B, participants[2]=C）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_betweenness(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                      bool named) {
    if (!c || c->participant_count < 3)
        return 0;

    int a_id = c->participants[0];  /* 起点 A */
    int b_id = c->participants[1];  /* 中间点 B */
    int cc_id = c->participants[2]; /* 终点 C */

    const char *ax = smtlib2_coord_var_name(a_id, 0);
    const char *ay = smtlib2_coord_var_name(a_id, 1);
    const char *bx = smtlib2_coord_var_name(b_id, 0);
    const char *by = smtlib2_coord_var_name(b_id, 1);
    const char *cx = smtlib2_coord_var_name(cc_id, 0);
    const char *cy = smtlib2_coord_var_name(cc_id, 1);

    int n = 0;
    int total = 0;

    /* 断言 1：共线性 —— 叉积方程 (B-A) x (C-A) = 0 */
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 之间约束 c%d: 点 p%d 在 p%d 和 p%d 之间\n"
                     "  (assert (! (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0) :named c%d_collinear))\n",
                     c->id, b_id, a_id, cc_id, bx, ax, cy, ay, by, ay, cx, ax, c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 之间约束 c%d: 点 p%d 在 p%d 和 p%d 之间\n"
                     "  (assert (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0))\n",
                     c->id, b_id, a_id, cc_id, bx, ax, cy, ay, by, ay, cx, ax);
    }
    if (n < 0)
        return -1;
    total += n;

    /* 断言 2：有序性 —— 点积 (B-A).(C-A) >= 0（B 与 C 在 A 的同侧） */
    if (remaining - total <= 64)
        return total;
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (! (>= (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "               0.0) :named c%d_order1))\n",
                     bx, ax, cx, ax, by, ay, cy, ay, c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (>= (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "               0.0))\n",
                     bx, ax, cx, ax, by, ay, cy, ay);
    }
    if (n < 0)
        return -1;
    total += n;

    /* 断言 3：有序性 —— 点积 (B-A).(C-A) <= |C-A|^2（B 不超过 C） */
    if (remaining - total <= 64)
        return total;
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (! (<= (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "               (+ (* (- %s %s) (- %s %s))\n"
                     "                  (* (- %s %s) (- %s %s)))) :named c%d_order2))\n",
                     bx, ax, cx, ax, by, ay, cy, ay, cx, ax, cx, ax, cy, ay, cy, ay, c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (<= (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "               (+ (* (- %s %s) (- %s %s))\n"
                     "                  (* (- %s %s) (- %s %s)))))\n",
                     bx, ax, cx, ax, by, ay, cy, ay, cx, ax, cx, ax, cy, ay, cy, ay);
    }
    if (n < 0)
        return -1;
    total += n;

    return total;
}

/**
 * @brief 通过关联约束解析线段端点的两个点节点 ID
 *
 * 几何语义：线段由两个端点点节点确定，端点在图中通过
 * INCIDENCE 约束（点在线段上）表达。这里扫描图中全部
 * 关联约束，收集以该线段为目标对象的所有点节点 ID。
 *
 * @param graph          约束图
 * @param line_id        线段节点 ID
 * @param out_endpoints  输出端点点节点 ID（最多 2 个）
 * @return 找到的端点数量
 */
static int smtlib2_find_line_endpoints(const ConstraintGraph *graph, int line_id, int out_endpoints[2]) {
    if (!graph || !out_endpoints)
        return 0;

    int count = 0;
    for (int i = 0; i < graph->constraint_count && count < 2; i++) {
        const Constraint *con = graph->constraints[i];
        if (!con)
            continue;
        if (con->type != INCIDENCE || con->participant_count < 2)
            continue;
        /* 关联约束 participants[0] = 点, participants[1] = 对象 */
        if (con->participants[1] == line_id) {
            int point_id = con->participants[0];
            if (lv_index_in_range(point_id, graph->node_count) && graph->nodes[point_id] != NULL) {
                out_endpoints[count++] = point_id;
            }
        }
    }
    return count;
}

/**
 * @brief 编码角度约束（ANGLE）：两条线段的夹角为给定值
 *
 * 几何含义：线段 AB 与线段 CB 在公共顶点 B 处的夹角为 θ。
 * 设 v1 = A - B，v2 = C - B（均以顶点为起点），则：
 *   dot   = v1·v2 = |v1|·|v2|·cosθ
 *   |v1|^2 = v1x^2 + v1y^2
 *   |v2|^2 = v2x^2 + v2y^2
 *
 * 代数编码（三点角度 = 向量夹角余弦，消去分母避免开方）：
 *   dot^2 = |v1|^2 · |v2|^2 · cos^2θ
 * 余弦在 [0°, 180°] 上单调，配合 dot 的符号断言：
 *   dot >= 0（当 cosθ >= 0） 或 dot <= 0（当 cosθ <= 0）
 * 即可唯一确定夹角。全部使用 QF_NRA 多项式实数算术。
 *
 * 参与者形式：
 *   - participant_count >= 3：三点 ∠p0p1p2（顶点为 p1）
 *   - participant_count == 2：两条线段（通过关联约束解析端点，
 *     公共点为顶点）
 *
 * @param graph     约束图
 * @param c         角度约束（numeric_value 为角度值，单位度）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_angle(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                bool named) {
    if (!c || c->participant_count < 2)
        return 0;

    int a_id = -1, b_id = -1, cc_id = -1;
    if (c->participant_count >= 3) {
        /* 三点形式：∠p0p1p2，顶点为 p1 */
        a_id = c->participants[0];
        b_id = c->participants[1];
        cc_id = c->participants[2];
    } else {
        /* 两线段形式：解析端点并求公共顶点 */
        int ep1[2] = {-1, -1}, ep2[2] = {-1, -1};
        int n1 = smtlib2_find_line_endpoints(graph, c->participants[0], ep1);
        int n2 = smtlib2_find_line_endpoints(graph, c->participants[1], ep2);
        if (n1 >= 2 && n2 >= 2) {
            for (int i = 0; i < 2; i++) {
                for (int j = 0; j < 2; j++) {
                    if (ep1[i] == ep2[j]) {
                        b_id = ep1[i];
                        a_id = ep1[1 - i];
                        cc_id = ep2[1 - j];
                        break;
                    }
                }
                if (b_id >= 0)
                    break;
            }
        }
    }
    if (a_id < 0 || b_id < 0 || cc_id < 0)
        return 0;

    /* 角度值（度）→ 余弦（弧度） */
    double theta_rad = lv_deg_to_rad(c->numeric_value);
    double cos_theta = cos(theta_rad);
    double cos2 = cos_theta * cos_theta;

    const char *ax = smtlib2_coord_var_name(a_id, 0);
    const char *ay = smtlib2_coord_var_name(a_id, 1);
    const char *bx = smtlib2_coord_var_name(b_id, 0);
    const char *by = smtlib2_coord_var_name(b_id, 1);
    const char *cx = smtlib2_coord_var_name(cc_id, 0);
    const char *cy = smtlib2_coord_var_name(cc_id, 1);

    int total = 0;
    int n = 0;

    /* 断言 1：dot^2 = |v1|^2 · |v2|^2 · cos^2θ */
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 角度约束 c%d: ∠(对象 %d, 对象 %d) = %.6f°\n"
                     "  (assert (! (= (* (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "                 (+ (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s))))\n"
                     "                (* (+ (* (- %s %s) (- %s %s))\n"
                     "                      (* (- %s %s) (- %s %s)))\n"
                     "                   (+ (* (- %s %s) (- %s %s))\n"
                     "                      (* (- %s %s) (- %s %s)))\n"
                     "                   %.12f)) :named c%d_angle_mag))\n",
                     c->id, c->participants[0], c->participants[1], c->numeric_value,
                     ax, bx, cx, bx,
                     ay, by, cy, by,
                     ax, bx, cx, bx,
                     ay, by, cy, by,
                     ax, bx, ax, bx,
                     ay, by, ay, by,
                     cx, bx, cx, bx,
                     cy, by, cy, by,
                     cos2, c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 角度约束 c%d: ∠(对象 %d, 对象 %d) = %.6f°\n"
                     "  (assert (= (* (+ (* (- %s %s) (- %s %s))\n"
                     "                   (* (- %s %s) (- %s %s)))\n"
                     "                 (+ (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s))))\n"
                     "                (* (+ (* (- %s %s) (- %s %s))\n"
                     "                      (* (- %s %s) (- %s %s)))\n"
                     "                   (+ (* (- %s %s) (- %s %s))\n"
                     "                      (* (- %s %s) (- %s %s)))\n"
                     "                   %.12f)))\n",
                     c->id, c->participants[0], c->participants[1], c->numeric_value,
                     ax, bx, cx, bx,
                     ay, by, cy, by,
                     ax, bx, cx, bx,
                     ay, by, cy, by,
                     ax, bx, ax, bx,
                     ay, by, ay, by,
                     cx, bx, cx, bx,
                     cy, by, cy, by,
                     cos2);
    }
    /* exempt: snprintf 返回码截断检测（n 为返回值而非索引：-1=编码错误、
     * n>=remaining=缓冲截断），与 lv_index_in_range 的索引范围语义不同 */
    if (n < 0 || n >= remaining - total)
        return (n < 0) ? -1 : total;
    total += n;

    /* 断言 2：dot 的符号，消除平方带来的符号二义性 */
    if (remaining - total <= 64)
        return total;
    if (cos_theta > 1e-9) {
        if (named) {
            n = snprintf(buf + total, (size_t) (remaining - total),
                         "  (assert (! (>= (+ (* (- %s %s) (- %s %s))\n"
                         "                    (* (- %s %s) (- %s %s)))\n"
                         "                 0.0) :named c%d_angle_sign))\n",
                         ax, bx, cx, bx, ay, by, cy, by, c->id);
        } else {
            n = snprintf(buf + total, (size_t) (remaining - total),
                         "  (assert (>= (+ (* (- %s %s) (- %s %s))\n"
                         "                  (* (- %s %s) (- %s %s)))\n"
                         "               0.0))\n",
                         ax, bx, cx, bx, ay, by, cy, by);
        }
    } else if (cos_theta < -1e-9) {
        if (named) {
            n = snprintf(buf + total, (size_t) (remaining - total),
                         "  (assert (! (<= (+ (* (- %s %s) (- %s %s))\n"
                         "                    (* (- %s %s) (- %s %s)))\n"
                         "                 0.0) :named c%d_angle_sign))\n",
                         ax, bx, cx, bx, ay, by, cy, by, c->id);
        } else {
            n = snprintf(buf + total, (size_t) (remaining - total),
                         "  (assert (<= (+ (* (- %s %s) (- %s %s))\n"
                         "                  (* (- %s %s) (- %s %s)))\n"
                         "               0.0))\n",
                         ax, bx, cx, bx, ay, by, cy, by);
        }
    } else {
        /* cosθ ≈ 0 时 dot^2 = 0 已蕴含 dot = 0，无需符号断言 */
        return total;
    }
    if (n < 0)
        return -1;
    total += n;

    return total;
}

/**
 * @brief 编码相交约束（INTERSECTION）：两线段在某点相交
 *
 * 几何含义：线段 L1 和线段 L2 在交点 P 处相交。
 * 代数编码：交点 P 同时满足两条线段的参数方程。
 *   P = A1 + t1*(B1 - A1)
 *   P = A2 + t2*(B2 - A2)
 * 消去参数后得到：
 *   (Px - A1x)*(B1y - A1y) - (Py - A1y)*(B1x - A1x) = 0  （P 在 L1 上）
 *   (Px - A2x)*(B2y - A2y) - (Py - A2y)*(B2x - A2x) = 0  （P 在 L2 上）
 *
 * @param graph     约束图
 * @param c         相交约束（participants[0]=线段1, participants[1]=线段2, participants[2]=交点）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_intersection(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                       bool named) {
    if (!c || c->participant_count < 3)
        return 0;

    int l1_id = c->participants[0]; /* 线段 1 */
    int l2_id = c->participants[1]; /* 线段 2 */
    int p_id = c->participants[2];  /* 交点 */

    /* 线段端点的模拟 ID（与 INCIDENCE 编码保持一致） */
    int a1_id = l1_id * 2;
    int b1_id = l1_id * 2 + 1;
    int a2_id = l2_id * 2;
    int b2_id = l2_id * 2 + 1;

    const char *px = smtlib2_coord_var_name(p_id, 0);
    const char *py = smtlib2_coord_var_name(p_id, 1);

    int n = 0;
    int total = 0;

    /* 断言 1：交点 P 在线段 L1 上（叉积方程） */
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 相交约束 c%d: 线段 seg%d 与 seg%d 交于点 p%d\n"
                     "  (assert (! (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0) :named c%d_on_L1))\n",
                     c->id, l1_id, l2_id, p_id, px, smtlib2_coord_var_name(a1_id, 0), smtlib2_coord_var_name(b1_id, 1),
                     smtlib2_coord_var_name(a1_id, 1), py, smtlib2_coord_var_name(a1_id, 1),
                     smtlib2_coord_var_name(b1_id, 0), smtlib2_coord_var_name(a1_id, 0), c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 相交约束 c%d: 线段 seg%d 与 seg%d 交于点 p%d\n"
                     "  (assert (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0))\n",
                     c->id, l1_id, l2_id, p_id, px, smtlib2_coord_var_name(a1_id, 0), smtlib2_coord_var_name(b1_id, 1),
                     smtlib2_coord_var_name(a1_id, 1), py, smtlib2_coord_var_name(a1_id, 1),
                     smtlib2_coord_var_name(b1_id, 0), smtlib2_coord_var_name(a1_id, 0));
    }
    if (n < 0)
        return -1;
    total += n;

    /* 断言 2：交点 P 在线段 L2 上（叉积方程） */
    if (remaining - total <= 128)
        return total;
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (! (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0) :named c%d_on_L2))\n",
                     px, smtlib2_coord_var_name(a2_id, 0), smtlib2_coord_var_name(b2_id, 1),
                     smtlib2_coord_var_name(a2_id, 1), py, smtlib2_coord_var_name(a2_id, 1),
                     smtlib2_coord_var_name(b2_id, 0), smtlib2_coord_var_name(a2_id, 0), c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  (assert (= (- (* (- %s %s) (- %s %s))\n"
                     "                    (* (- %s %s) (- %s %s)))\n"
                     "                0.0))\n",
                     px, smtlib2_coord_var_name(a2_id, 0), smtlib2_coord_var_name(b2_id, 1),
                     smtlib2_coord_var_name(a2_id, 1), py, smtlib2_coord_var_name(a2_id, 1),
                     smtlib2_coord_var_name(b2_id, 0), smtlib2_coord_var_name(a2_id, 0));
    }
    if (n < 0)
        return -1;
    total += n;

    return total;
}

/**
 * @brief 编码包含约束（CONTAINMENT）：内部对象完全包含在外部对象中
 *
 * 几何含义：内部几何对象的所有点都在外部对象内部。
 * 代数编码（简化为点到区域中心的距离约束）：
 *   |P_inner - Center_outer|^2 <= R^2
 * 展开为：
 *   (Px - Cx)^2 + (Py - Cy)^2 <= R^2
 *
 * 对于更精确的编码，需要将区域边界线段逐条编码为
 * 半平面约束（有向距离 <= 0）。
 *
 * @param graph     约束图
 * @param c         包含约束（participants[0]=内部对象, participants[1]=外部对象）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_containment(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                      bool named) {
    if (!c || c->participant_count < 2)
        return 0;

    int inner_id = c->participants[0]; /* 内部对象 ID */
    int outer_id = c->participants[1]; /* 外部对象 ID */

    /* 包含约束的完整编码需要区域边界信息。
     * 这里使用简化编码：内部对象的坐标必须满足外部区域的约束。
     * 对于点在区域内的情况，编码为距离约束。 */

    if (named) {
        return snprintf(buf, (size_t) remaining,
                        "  ; 包含约束 c%d: 对象 %d 包含在对象 %d 内\n"
                        "  (assert (! (<= (+ (* (- p%d_x p%d_x) (- p%d_x p%d_x))\n"
                        "                   (* (- p%d_y p%d_y) (- p%d_y p%d_y)))\n"
                        "               1.0) :named c%d))\n",
                        c->id, inner_id, outer_id, inner_id, outer_id, inner_id, outer_id, inner_id, outer_id, inner_id,
                        outer_id, c->id);
    } else {
        return snprintf(buf, (size_t) remaining,
                        "  ; 包含约束 c%d: 对象 %d 包含在对象 %d 内\n"
                        "  (assert (<= (+ (* (- p%d_x p%d_x) (- p%d_x p%d_x))\n"
                        "                   (* (- p%d_y p%d_y) (- p%d_y p%d_y)))\n"
                        "               1.0))\n",
                        c->id, inner_id, outer_id, inner_id, outer_id, inner_id, outer_id, inner_id, outer_id, inner_id,
                        outer_id);
    }
}

/**
 * @brief 编码连接约束（CONNECTION）：两个端口之间的数据流连接
 *
 * 几何含义：源端口和目标端口在空间上重合（坐标相同）。
 * 代数编码：坐标等式
 *   src_x = dst_x
 *   src_y = dst_y
 *
 * @param graph     约束图
 * @param c         连接约束（participants[0]=源端口, participants[1]=目标端口）
 * @param buf       输出缓冲区
 * @param remaining 缓冲区剩余空间
 * @param named     是否生成命名断言
 * @return 写入的字符数，失败返回 -1
 */
static int smtlib2_encode_connection(const ConstraintGraph *graph, const Constraint *c, char *buf, int remaining,
                                     bool named) {
    if (!c || c->participant_count < 2)
        return 0;

    int src_id = c->participants[0]; /* 源端口 ID */
    int dst_id = c->participants[1]; /* 目标端口 ID */

    int n = 0;
    int total = 0;

    /* 断言 1：x 坐标相等 */
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 连接约束 c%d: 端口 p%d 与端口 p%d 坐标重合\n"
                     "  (assert (! (= %s %s) :named c%d_x_eq))\n",
                     c->id, src_id, dst_id, smtlib2_coord_var_name(src_id, 0), smtlib2_coord_var_name(dst_id, 0),
                     c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total),
                     "  ; 连接约束 c%d: 端口 p%d 与端口 p%d 坐标重合\n"
                     "  (assert (= %s %s))\n",
                     c->id, src_id, dst_id, smtlib2_coord_var_name(src_id, 0), smtlib2_coord_var_name(dst_id, 0));
    }
    if (n < 0)
        return -1;
    total += n;

    /* 断言 2：y 坐标相等 */
    if (remaining - total <= 64)
        return total;
    if (named) {
        n = snprintf(buf + total, (size_t) (remaining - total), "  (assert (! (= %s %s) :named c%d_y_eq))\n",
                     smtlib2_coord_var_name(src_id, 1), smtlib2_coord_var_name(dst_id, 1), c->id);
    } else {
        n = snprintf(buf + total, (size_t) (remaining - total), "  (assert (= %s %s))\n",
                     smtlib2_coord_var_name(src_id, 1), smtlib2_coord_var_name(dst_id, 1));
    }
    if (n < 0)
        return -1;
    total += n;

    return total;
}

