/**
 * @file atp_backend.c
 * @brief 一阶逻辑自动定理证明器（FOL ATP）后端抽象层实现
 *
 * @details 实现 atp_backend.h 中声明的所有 ATP 后端接口。
 *          借鉴 Vampire、E Prover、iProver 的架构设计，提供 FOL ATP 的
 *          统一后端抽象。当前版本为框架实现（桩代码），实际证明需链接
 *          外部 ATP 可执行文件。
 *
 *          与 SMT 后端的分工：
 *          - ATP 处理纯逻辑推导和一阶量词推理
 *          - SMT 处理算术/非线性约束
 *
 *          编码格式：TPTP FOF/CNF/TFF（与 Vampire/E Prover 兼容）
 *
 * @author Lv-00 Project
 * @version 3.3.0
 * @date 2026-05-24
 *
 * @dependencies
 *   - atp_backend.h          : ATP 后端公共接口
 *   - lv00_internal.h        : 内部常量与工具宏
 *   - lv00_utils.h           : 统一内存分配器
 *   - error_codes.h          : 统一错误码系统
 *   - proof.h                : Lv-00 证明系统
 */

#include "atp_backend.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "error_codes.h"
#include "lv00_internal.h"
#include "lv00_utils.h"

/* ============================================================
 * 模块级常量
 * ============================================================ */

/** @brief 默认求解超时（秒） */
#define ATP_DEFAULT_TIMEOUT 30.0

/** @brief 默认内存限制（MB） */
#define ATP_DEFAULT_MEMORY_MB 1024

/** @brief TPTP 编码缓冲区默认大小 */
#define ATP_TPTP_BUFFER_SIZE 65536

/** @brief 全局注册表最大条目数 */
#define ATP_REGISTRY_MAX_ENTRIES 8

/* ============================================================
 * 不透明结构：ATPBackendSolver 内部实现
 * ============================================================ */

/**
 * @brief ATP 求解器内部状态
 */
struct ATPBackendSolver {
    ATPBackendType type;        /**< 后端类型 */
    ATPConfig config;           /**< 求解器配置 */
    char *tptp_code;            /**< 已加载的 TPTP 编码 */
    int tptp_len;               /**< TPTP 编码长度 */
    bool is_initialized;        /**< 是否已初始化 */
    bool has_problem;           /**< 是否已加载问题 */
};

/* ============================================================
 * 全局后端注册表（单例）
 * ============================================================ */

/** @brief 全局静态注册表 */
static ATPBackendRegistry g_atp_registry;
static bool g_atp_registry_initialized = false;

/* ============================================================
 * 默认配置
 * ============================================================ */

/**
 * @brief 创建默认 ATP 配置
 *
 * 默认使用 TPTP FOF 格式、30 秒超时、自动策略选择、生成证明。
 */
ATPConfig atp_config_default(void) {
    ATPConfig cfg;
    memset(&cfg, 0, sizeof(ATPConfig));
    cfg.input_format = ATP_FORMAT_TPTP_FOF;
    cfg.timeout_seconds = ATP_DEFAULT_TIMEOUT;
    cfg.memory_limit_mb = ATP_DEFAULT_MEMORY_MB;
    cfg.auto_strategy = true;
    cfg.strategy_name = NULL;
    cfg.produce_proof = true;
    cfg.produce_unsat_core = false;
    cfg.use_avatar = false;
    cfg.clause_weight_limit = 0;
    cfg.custom_options = NULL;
    cfg.verbosity = 0;
    cfg.log_file = NULL;
    return cfg;
}

/* ============================================================
 * 约束图 -> TPTP 编码
 * ============================================================ */

/**
 * @brief 将约束图编码为 TPTP FOF/CNF/TFF 格式字符串
 *
 * 将 Lv-00 的几何约束图编码为 TPTP 格式：
 * - 节点 -> 常量符号
 * - 几何类型 -> 一元谓词
 * - 约束 -> 二元/三元谓词
 * - 公理 -> TPTP axiom 子句
 *
 * 框架实现：生成基本 TPTP 骨架。
 */
char *atp_encode_constraint_graph(const ConstraintGraph *graph, ATPInputFormat format,
                                   const char *problem_name, bool include_proof_goal,
                                   const Proposition *target_prop) {
    LV00_CHECK_NULL(graph, NULL);

    char *buf = (char *)lv00_malloc(ATP_TPTP_BUFFER_SIZE);
    if (!buf) {
        return NULL;
    }

    int offset = 0;
    int remaining = ATP_TPTP_BUFFER_SIZE;

    /* 根据格式选择头部 */
    const char *lang;
    switch (format) {
    case ATP_FORMAT_TPTP_FOF: lang = "fof"; break;
    case ATP_FORMAT_TPTP_CNF: lang = "cnf"; break;
    case ATP_FORMAT_TPTP_TFF: lang = "tff"; break;
    default:                  lang = "fof"; break;
    }

    const char *name = problem_name ? problem_name : "lv00_geometry";
    int n = snprintf(buf + offset, (size_t)remaining,
                     "%% TPTP %s encoding for Lv-00 constraint graph\n"
                     "%% Generated by Lv-00 ATP backend\n\n",
                     lang);
    if (n > 0 && n < remaining) { offset += n; remaining -= n; }

    /* 类型声明（TFF 格式） */
    if (format == ATP_FORMAT_TPTP_TFF && remaining > 128) {
        n = snprintf(buf + offset, (size_t)remaining,
                     "tff(point_type, type, point: $tType).\n"
                     "tff(line_type, type, line: $tType).\n\n");
        if (n > 0 && n < remaining) { offset += n; remaining -= n; }
    }

    /* 声明节点常量 */
    int node_count = graph->node_count;
    for (int i = 0; i < node_count && remaining > 64; i++) {
        n = snprintf(buf + offset, (size_t)remaining,
                     "%s(p%d_decl, axiom, point(p%d)).\n", lang, i, i);
        if (n > 0 && n < remaining) { offset += n; remaining -= n; }
    }

    /* 编码几何约束为谓词 */
    int edge_count = graph->constraint_count;
    for (int i = 0; i < edge_count && remaining > 128; i++) {
        n = snprintf(buf + offset, (size_t)remaining,
                     "%s(constraint_%d, axiom, incident(p%d, l%d)).\n",
                     lang, i, i % node_count, i % (node_count > 0 ? node_count : 1));
        if (n > 0 && n < remaining) { offset += n; remaining -= n; }
    }

    LV00_UNUSED(include_proof_goal);
    LV00_UNUSED(target_prop);

    /* 添加 conjecture（如果请求） */
    if (include_proof_goal && remaining > 128) {
        n = snprintf(buf + offset, (size_t)remaining,
                     "%s(goal, conjecture, $false).\n", lang);
        if (n > 0 && n < remaining) { offset += n; remaining -= n; }
    }

    return buf;
}

/* ============================================================
 * ATP 求解器生命周期
 * ============================================================ */

/**
 * @brief 创建 ATP 求解器实例
 *
 * 框架实现：分配并初始化求解器句柄。
 * 当前所有后端均为桩实现，待链接实际 ATP 可执行文件后
 * 将产生真实的证明结果。
 */
ATPBackendSolver *atp_solver_create(ATPBackendType type, const ATPConfig *config) {
    ATPBackendSolver *solver = (ATPBackendSolver *)lv00_malloc(sizeof(ATPBackendSolver));
    if (!solver) {
        return NULL;
    }

    memset(solver, 0, sizeof(ATPBackendSolver));
    solver->type = type;
    solver->is_initialized = true;
    solver->has_problem = false;

    if (config) {
        solver->config = *config;
    } else {
        solver->config = atp_config_default();
    }

    return solver;
}

/**
 * @brief 销毁 ATP 求解器
 */
void atp_solver_destroy(ATPBackendSolver *solver) {
    if (!solver) {
        return;
    }
    if (solver->tptp_code) {
        lv00_free((void **)&solver->tptp_code);
    }
    lv00_free((void **)&solver);
}

/**
 * @brief 获取求解器后端类型
 */
ATPBackendType atp_solver_get_type(const ATPBackendSolver *solver) {
    if (!solver) {
        return ATP_BACKEND_COUNT;
    }
    return solver->type;
}

/* ============================================================
 * ATP 求解操作
 * ============================================================ */

/**
 * @brief 将 TPTP 编码加载到求解器
 *
 * 框架实现：存储 TPTP 文本副本，不进行实际解析。
 */
int atp_solver_load(ATPBackendSolver *solver, const char *tptp_text) {
    LV00_CHECK_NULL(solver, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(tptp_text, (int)LV00_ERROR_NULL_POINTER);

    if (!solver->is_initialized) {
        return (int)LV00_ERROR_NOT_INITIALIZED;
    }

    /* 释放旧编码 */
    if (solver->tptp_code) {
        lv00_free((void **)&solver->tptp_code);
    }

    int len = (int)strlen(tptp_text);
    if (len <= 0) {
        return (int)LV00_ERROR_INVALID_ARGUMENT;
    }

    solver->tptp_code = (char *)lv00_malloc((size_t)(len + 1));
    if (!solver->tptp_code) {
        return (int)LV00_ERROR_OUT_OF_MEMORY;
    }

    memcpy(solver->tptp_code, tptp_text, (size_t)(len + 1));
    solver->tptp_len = len;
    solver->has_problem = true;

    return (int)LV00_OK;
}

/**
 * @brief 执行 ATP 求解
 *
 * 框架实现：桩代码，返回 ATP_RESULT_UNKNOWN。
 * 实际链接后将通过外部进程调用 ATP 可执行文件并解析结果。
 */
int atp_solver_solve(ATPBackendSolver *solver, ATPResultInfo *result) {
    LV00_CHECK_NULL(solver, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(result, (int)LV00_ERROR_NULL_POINTER);

    atp_result_init(result);

    if (!solver->is_initialized) {
        result->result = ATP_RESULT_ERROR;
        result->error_code = (int)LV00_ERROR_NOT_INITIALIZED;
        snprintf(result->error_message, sizeof(result->error_message),
                 "ATP solver not initialized");
        return (int)LV00_ERROR_NOT_INITIALIZED;
    }

    if (!solver->has_problem) {
        result->result = ATP_RESULT_ERROR;
        result->error_code = (int)LV00_ERROR_INVALID_STATE;
        snprintf(result->error_message, sizeof(result->error_message),
                 "No problem loaded");
        return (int)LV00_ERROR_INVALID_STATE;
    }

    result->backend = solver->type;

    /* 桩：返回 UNKNOWN */
    result->result = ATP_RESULT_UNKNOWN;
    result->solve_time_seconds = 0.0;
    result->generated_clauses = 0;
    result->processed_clauses = 0;
    result->kept_clauses = 0;

    snprintf(result->error_message, sizeof(result->error_message),
             "ATP backend '%s' is a stub; returning UNKNOWN",
             atp_backend_type_name(solver->type));

    return (int)LV00_OK;
}

/**
 * @brief 便捷函数：编码 + 加载 + 求解
 */
int atp_solver_solve_graph(ATPBackendSolver *solver, const ConstraintGraph *graph,
                            ATPInputFormat format, const char *problem_name,
                            bool include_goal, const Proposition *target_prop,
                            ATPResultInfo *result) {
    LV00_CHECK_NULL(solver, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(graph, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(result, (int)LV00_ERROR_NULL_POINTER);

    /* 步骤 1：编码 */
    char *tptp = atp_encode_constraint_graph(graph, format, problem_name,
                                              include_goal, target_prop);
    if (!tptp) {
        atp_result_init(result);
        result->result = ATP_RESULT_ERROR;
        result->error_code = (int)LV00_ERROR_OUT_OF_MEMORY;
        snprintf(result->error_message, sizeof(result->error_message),
                 "TPTP encoding failed");
        return (int)LV00_ERROR_OUT_OF_MEMORY;
    }

    /* 步骤 2：加载 */
    int rc = atp_solver_load(solver, tptp);
    lv00_free((void **)&tptp);

    if (rc != (int)LV00_OK) {
        atp_result_init(result);
        result->result = ATP_RESULT_ERROR;
        result->error_code = rc;
        snprintf(result->error_message, sizeof(result->error_message),
                 "Failed to load TPTP encoding");
        return rc;
    }

    /* 步骤 3：求解 */
    return atp_solver_solve(solver, result);
}

/* ============================================================
 * 结果处理与转换
 * ============================================================ */

/**
 * @brief 初始化 ATP 求解结果
 */
void atp_result_init(ATPResultInfo *result) {
    if (!result) {
        return;
    }
    memset(result, 0, sizeof(ATPResultInfo));
    result->result = ATP_RESULT_UNKNOWN;
    result->backend = ATP_BACKEND_COUNT;
}

/**
 * @brief 释放 ATP 求解结果中的动态资源
 */
void atp_result_free(ATPResultInfo *result) {
    if (!result) {
        return;
    }
    if (result->proof_steps) {
        for (int i = 0; i < result->proof_step_count; i++) {
            if (result->proof_steps[i].clause) {
                lv00_free((void **)&result->proof_steps[i].clause);
            }
            if (result->proof_steps[i].inference_rule) {
                lv00_free((void **)&result->proof_steps[i].inference_rule);
            }
            if (result->proof_steps[i].justification) {
                lv00_free((void **)&result->proof_steps[i].justification);
            }
        }
        lv00_free((void **)&result->proof_steps);
    }
    result->proof_step_count = 0;
    if (result->unsat_core_clause_ids) {
        lv00_free((void **)&result->unsat_core_clause_ids);
    }
    result->unsat_core_count = 0;
    if (result->raw_output) {
        lv00_free((void **)&result->raw_output);
    }
    result->raw_output_length = 0;
}

/**
 * @brief 将 ATP 证明转换为 Lv-00 ProofNavigator 步骤
 *
 * 解析 TSTP 格式的 ATP 证明输出，转换为 Lv-00 证明步骤。
 * 框架实现：桩代码，当前不做实际转换。
 */
int atp_proof_to_lv00(const ATPResultInfo *result, Proof *proof, int *step_count) {
    LV00_CHECK_NULL(result, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(proof, (int)LV00_ERROR_NULL_POINTER);

    if (step_count) {
        *step_count = 0;
    }

    if (result->result != ATP_RESULT_UNSAT) {
        LV00_ERROR_SET(LV00_ERROR_INVALID_STATE,
                        "Proof conversion requires UNSAT result");
        return (int)LV00_ERROR_INVALID_STATE;
    }

    if (!result->proof_steps || result->proof_step_count == 0) {
        /* 桩：未生成证明步骤 */
        return (int)LV00_ERROR_NOT_FOUND;
    }

    /* 遍历 ATP 证明步骤并转换为 Lv-00 格式 */
    /* 框架实现：仅计算步骤数量 */
    int count = 0;
    for (int i = 0; i < result->proof_step_count; i++) {
        if (result->proof_steps[i].clause) {
            count++;
        }
    }

    if (step_count) {
        *step_count = count;
    }

    return (int)LV00_OK;
}

/* ============================================================
 * 后端注册与发现
 * ============================================================ */

/**
 * @brief 获取全局 ATP 后端注册表
 */
const ATPBackendRegistry *atp_get_registry(void) {
    if (!g_atp_registry_initialized) {
        memset(&g_atp_registry, 0, sizeof(g_atp_registry));
        g_atp_registry.count = 0;
        g_atp_registry_initialized = true;
    }
    return &g_atp_registry;
}

/**
 * @brief 注册自定义 ATP 后端
 */
int atp_register_backend(const ATPBackendEntry *entry) {
    LV00_CHECK_NULL(entry, (int)LV00_ERROR_NULL_POINTER);

    if (!g_atp_registry_initialized) {
        atp_get_registry(); /* 初始化 */
    }

    /* 检查是否已存在 */
    for (int i = 0; i < g_atp_registry.count; i++) {
        if (g_atp_registry.entries[i].type == entry->type) {
            return (int)LV00_ERROR_ALREADY_EXISTS;
        }
    }

    if (g_atp_registry.count >= ATP_BACKEND_COUNT) {
        return (int)LV00_ERROR_RESOURCE_EXHAUSTED;
    }

    g_atp_registry.entries[g_atp_registry.count] = *entry;
    g_atp_registry.count++;

    return (int)LV00_OK;
}

/**
 * @brief 检查后端在系统上是否可用
 *
 * 框架实现：所有后端均标记为不可用（桩）。
 * 实际链接后将通过 which/where 命令检查可执行文件。
 */
bool atp_is_backend_available(ATPBackendType type) {
    switch (type) {
    case ATP_BACKEND_VAMPIRE:
    case ATP_BACKEND_EPROVER:
    case ATP_BACKEND_IPROVER:
    case ATP_BACKEND_CUSTOM:
        return false; /* 桩：未链接任何 ATP */
    default:
        return false;
    }
}

/**
 * @brief 查找后端条目
 */
const ATPBackendEntry *atp_find_backend(ATPBackendType type) {
    if (!g_atp_registry_initialized) {
        return NULL;
    }

    for (int i = 0; i < g_atp_registry.count; i++) {
        if (g_atp_registry.entries[i].type == type) {
            return &g_atp_registry.entries[i];
        }
    }
    return NULL;
}

/**
 * @brief 获取后端类型名称
 */
const char *atp_backend_type_name(ATPBackendType type) {
    switch (type) {
    case ATP_BACKEND_VAMPIRE: return "Vampire";
    case ATP_BACKEND_EPROVER: return "E Prover";
    case ATP_BACKEND_IPROVER: return "iProver";
    case ATP_BACKEND_CUSTOM:  return "Custom";
    default:                  return "Unknown";
    }
}

/**
 * @brief 从名称字符串解析后端类型
 */
bool atp_backend_type_from_name(const char *name, ATPBackendType *out_type) {
    if (!name || !out_type) {
        return false;
    }

    if (strcasecmp(name, "vampire") == 0) {
        *out_type = ATP_BACKEND_VAMPIRE;
        return true;
    }
    if (strcasecmp(name, "eprover") == 0 || strcasecmp(name, "e") == 0) {
        *out_type = ATP_BACKEND_EPROVER;
        return true;
    }
    if (strcasecmp(name, "iprover") == 0) {
        *out_type = ATP_BACKEND_IPROVER;
        return true;
    }
    if (strcasecmp(name, "custom") == 0) {
        *out_type = ATP_BACKEND_CUSTOM;
        return true;
    }
    return false;
}

/* ============================================================
 * 引擎调度器集成
 * ============================================================ */

/**
 * @brief 将所有可用 ATP 后端注册到引擎调度器
 *
 * 框架实现：检查系统上可用的 ATP 后端并注册。
 * 当前无 ATP 后端可用，返回 0。
 */
int atp_register_all_to_scheduler(void) {
    int registered = 0;

    /* 尝试注册所有 ATP 后端 */
    ATPBackendType types[] = {
        ATP_BACKEND_VAMPIRE, ATP_BACKEND_EPROVER,
        ATP_BACKEND_IPROVER, ATP_BACKEND_CUSTOM
    };

    for (size_t i = 0; i < sizeof(types) / sizeof(types[0]); i++) {
        if (atp_is_backend_available(types[i])) {
            ATPBackendEntry entry;
            memset(&entry, 0, sizeof(entry));
            entry.type = types[i];
            entry.available = true;
            entry.create = NULL; /* 工厂函数由各后端模块提供 */
            entry.priority = (int)i + 1;
            entry.description = atp_backend_type_name(types[i]);

            if (atp_register_backend(&entry) == (int)LV00_OK) {
                registered++;
            }
        }
    }

    return registered;
}

/**
 * @brief 自动选择最优后端并求解（ATP vs SMT）
 *
 * 决策逻辑：
 * 1. 纯逻辑约束 -> 优先 ATP
 * 2. 含非线性算术 -> 优先 SMT
 * 3. 混合约束 -> 同时尝试，返回最先成功的结果
 *
 * 框架实现：桩代码，返回 ATP_RESULT_UNKNOWN。
 */
int atp_auto_solve(const ConstraintGraph *graph, const ATPConfig *config,
                    ATPResultInfo *result) {
    LV00_CHECK_NULL(graph, (int)LV00_ERROR_NULL_POINTER);
    LV00_CHECK_NULL(result, (int)LV00_ERROR_NULL_POINTER);

    atp_result_init(result);

    /* 尝试 Vampire */
    if (atp_is_backend_available(ATP_BACKEND_VAMPIRE)) {
        ATPBackendSolver *solver = atp_solver_create(ATP_BACKEND_VAMPIRE, config);
        if (solver) {
            int rc = atp_solver_solve_graph(solver, graph, config ? config->input_format : ATP_FORMAT_TPTP_FOF,
                                             "lv00_auto", false, NULL, result);
            atp_solver_destroy(solver);
            return rc;
        }
    }

    /* 尝试 E Prover */
    if (atp_is_backend_available(ATP_BACKEND_EPROVER)) {
        ATPBackendSolver *solver = atp_solver_create(ATP_BACKEND_EPROVER, config);
        if (solver) {
            int rc = atp_solver_solve_graph(solver, graph, config ? config->input_format : ATP_FORMAT_TPTP_FOF,
                                             "lv00_auto", false, NULL, result);
            atp_solver_destroy(solver);
            return rc;
        }
    }

    /* 所有后端不可用：返回 UNKNOWN */
    result->result = ATP_RESULT_UNKNOWN;
    result->backend = ATP_BACKEND_COUNT;
    snprintf(result->error_message, sizeof(result->error_message),
             "No ATP backend available; returning UNKNOWN");

    return (int)LV00_OK;
}

/* ============================================================
 * 字符串工具
 * ============================================================ */

/**
 * @brief 获取结果类型名称
 */
const char *atp_result_name(ATPResult result) {
    switch (result) {
    case ATP_RESULT_SAT:     return "SAT";
    case ATP_RESULT_UNSAT:   return "UNSAT";
    case ATP_RESULT_UNKNOWN: return "UNKNOWN";
    case ATP_RESULT_ERROR:   return "ERROR";
    default:                 return "INVALID";
    }
}

/**
 * @brief 获取输入格式名称
 */
const char *atp_format_name(ATPInputFormat format) {
    switch (format) {
    case ATP_FORMAT_TPTP_FOF: return "TPTP FOF";
    case ATP_FORMAT_TPTP_CNF: return "TPTP CNF";
    case ATP_FORMAT_TPTP_TFF: return "TPTP TFF";
    case ATP_FORMAT_SMTLIB2:  return "SMT-LIB2";
    default:                  return "UNKNOWN";
    }
}
