/-!
# Lv-00 几何元语言形式化验证项目

本项目现在以 Lv-00 自有几何元语言理论为主线，而不是把 Hilbert 公理体系
作为主体直接复刻。Hilbert 相关文件仅保留在 `Classical/Hilbert` 中，作为
经典几何对照层与后续解释目标。

主线结构来自论文初稿：
1. 三元本体：点、线、域
2. 六条本原谓词：关联、之间、相交、包含、连接、等价
3. 八条基础公理/规则接口
4. 约束图与四态相容性
5. 归一化与多策略推理可靠性
6. 可追溯证明对象
-/

-- Lv-00 自有理论主线
import Lv00Formal.Theory.Ontology.Defs
import Lv00Formal.Theory.Predicates.Defs
import Lv00Formal.Theory.Axioms.Primitive
import Lv00Formal.Theory.Axioms.RuleTemplate
import Lv00Formal.Theory.Axioms.Instances
import Lv00Formal.Theory.Axioms.PackageValidation
import Lv00Formal.Theory.Constraint.Graph
import Lv00Formal.Theory.Constraint.Normalization
import Lv00Formal.Theory.Rewrite.Defs
import Lv00Formal.Theory.Unification.Defs
import Lv00Formal.Theory.Groebner.Defs
import Lv00Formal.Theory.Reasoning.Soundness
import Lv00Formal.Theory.Proof.Trace

-- 基础几何类型：仅作为工程互操作和外部解释的底层辅助
import Lv00Formal.Basic.Defs
import Lv00Formal.Basic.Notation

-- 经典对照层：不是主理论
import Lv00Formal.Classical.Hilbert.Incidence
import Lv00Formal.Classical.Hilbert.Consistency

-- 互操作验证接口
import Lv00Formal.Interop.FFI
import Lv00Formal.Interop.Equivalence

namespace Lv00Formal

-- 自有理论核心导出
export Theory.Ontology (ObjId OntKind LvPoint LvLine LvDomain LvObj WellFormedObj ontology_closed)
export Theory.Predicates (PrimPredKind PrimPred arity WellFormedPred predicate_closed)
export Theory.Axioms (BaseAxiomKind RuleLayer RuleRole canonicalKinds BaseAxiomRule WellFormedRule RuleKindCompatible RuleAbsorbable LvAxiomSystem rule_conclusion_closed wellformed_rule_absorbable system_rules_absorbable system_covers_all_kinds)
export Theory.Axioms.RuleTemplate (RuleType RuleStatus RulePriority ConditionType RuleVariable RuleCondition RulePremise RuleConclusion ExecutableRule WellFormedExecutableRule RuleMatch WellFormedMatch Applicable RuleApplication WellFormedApplication ConclusionAbsorbable absorbApplication application_outputs_absorbable absorbed_new_constraints_wellformed)
export Theory.Axioms.Instances (PackageTemplate UnconstructibleProblem AxiomPackageInstance proofTheoryTemplates proofTheoryUnconstructibles proofTheoryPackage proofTheoryExecutableRules linearLogicTemplates linearLogicUnconstructibles linearLogicPackage linearLogicExecutableRules galoisTheoryTemplates galoisTheoryUnconstructibles galoisTheoryPackage galoisTheoryExecutableRules euclideanPlaneTemplates euclideanPlaneUnconstructibles euclideanPlanePackage euclideanPlaneExecutableRules categoryTheoryTemplates categoryTheoryUnconstructibles categoryTheoryPackage categoryTheoryExecutableRules hyperbolicGeometryTemplates hyperbolicGeometryUnconstructibles hyperbolicGeometryPackage hyperbolicGeometryExecutableRules projectiveGeometryTemplates projectiveGeometryUnconstructibles projectiveGeometryPackage projectiveGeometryExecutableRules groupTheoryTemplates groupTheoryUnconstructibles groupTheoryPackage groupTheoryExecutableRules zfcSetTheoryTemplates zfcSetTheoryUnconstructibles zfcSetTheoryPackage zfcSetTheoryExecutableRules booleanAlgebraTemplates booleanAlgebraUnconstructibles booleanAlgebraPackage booleanAlgebraExecutableRules ringTheoryTemplates ringTheoryUnconstructibles ringTheoryPackage ringTheoryExecutableRules peanoArithmeticTemplates peanoArithmeticUnconstructibles peanoArithmeticPackage peanoArithmeticExecutableRules fieldTheoryTemplates fieldTheoryUnconstructibles fieldTheoryPackage fieldTheoryExecutableRules orderTheoryTemplates orderTheoryUnconstructibles orderTheoryPackage orderTheoryExecutableRules pointSetTopologyTemplates pointSetTopologyUnconstructibles pointSetTopologyPackage pointSetTopologyExecutableRules graphTheoryTemplates graphTheoryUnconstructibles graphTheoryPackage graphTheoryExecutableRules numberTheoryTemplates numberTheoryUnconstructibles numberTheoryPackage numberTheoryExecutableRules measureTheoryTemplates measureTheoryUnconstructibles measureTheoryPackage measureTheoryExecutableRules realAnalysisTemplates realAnalysisUnconstructibles realAnalysisPackage realAnalysisExecutableRules functionalAnalysisTemplates functionalAnalysisUnconstructibles functionalAnalysisPackage functionalAnalysisExecutableRules probabilityTheoryTemplates probabilityTheoryUnconstructibles probabilityTheoryPackage probabilityTheoryExecutableRules algebraicGeometryTemplates algebraicGeometryUnconstructibles algebraicGeometryPackage algebraicGeometryExecutableRules informationTheoryTemplates informationTheoryUnconstructibles informationTheoryPackage informationTheoryExecutableRules linearAlgebraTemplates linearAlgebraUnconstructibles linearAlgebraPackage linearAlgebraExecutableRules homologicalAlgebraTemplates homologicalAlgebraUnconstructibles homologicalAlgebraPackage homologicalAlgebraExecutableRules differentialGeometryTemplates differentialGeometryUnconstructibles differentialGeometryPackage differentialGeometryExecutableRules computabilityTheoryTemplates computabilityTheoryUnconstructibles computabilityTheoryPackage computabilityTheoryExecutableRules modalLogicTemplates modalLogicUnconstructibles modalLogicPackage modalLogicExecutableRules universalAlgebraTemplates universalAlgebraUnconstructibles universalAlgebraPackage universalAlgebraExecutableRules combinatoricsTemplates combinatoricsUnconstructibles combinatoricsPackage combinatoricsExecutableRules gameTheoryTemplates gameTheoryUnconstructibles gameTheoryPackage gameTheoryExecutableRules homotopyTypeTheoryTemplates homotopyTypeTheoryUnconstructibles homotopyTypeTheoryPackage homotopyTypeTheoryExecutableRules dependentTypeTheoryTemplates dependentTypeTheoryUnconstructibles dependentTypeTheoryPackage dependentTypeTheoryExecutableRules simpleTypeTheoryTemplates simpleTypeTheoryUnconstructibles simpleTypeTheoryPackage simpleTypeTheoryExecutableRules affineGeometryTemplates affineGeometryUnconstructibles affineGeometryPackage affineGeometryExecutableRules algebraicTopologyTemplates algebraicTopologyUnconstructibles algebraicTopologyPackage algebraicTopologyExecutableRules ellipticGeometryTemplates ellipticGeometryUnconstructibles ellipticGeometryPackage ellipticGeometryExecutableRules metricSpaceTemplates metricSpaceUnconstructibles metricSpacePackage metricSpaceExecutableRules latticeTheoryTemplates latticeTheoryUnconstructibles latticeTheoryPackage latticeTheoryExecutableRules lieTheoryTemplates lieTheoryUnconstructibles lieTheoryPackage lieTheoryExecutableRules modelTheoryTemplates modelTheoryUnconstructibles modelTheoryPackage modelTheoryExecutableRules classicalPropositionalLogicTemplates classicalPropositionalLogicUnconstructibles classicalPropositionalLogicPackage classicalPropositionalLogicExecutableRules intuitionisticLogicTemplates intuitionisticLogicUnconstructibles intuitionisticLogicPackage intuitionisticLogicExecutableRules toposTheoryTemplates toposTheoryUnconstructibles toposTheoryPackage toposTheoryExecutableRules)
export Theory.Axioms.PackageValidation (TemplateNameAvailable DependenciesSatisfied PackageDependenciesValid PackageValidationResult globalNameRegistry NameInGlobalRegistry CrossPackageDependenciesSatisfied CrossPackageDependenciesValid proofTheoryPackage_dependencies_valid proofTheoryValidationResult linearLogicPackage_dependencies_valid linearLogicValidationResult galoisTheoryPackage_dependencies_valid galoisTheoryValidationResult euclideanPlanePackage_dependencies_valid euclideanPlaneValidationResult categoryTheoryPackage_dependencies_valid categoryTheoryValidationResult hyperbolicGeometryPackage_dependencies_valid hyperbolicGeometryValidationResult projectiveGeometryPackage_dependencies_valid projectiveGeometryValidationResult groupTheoryPackage_dependencies_valid groupTheoryValidationResult zfcSetTheoryPackage_dependencies_valid zfcSetTheoryValidationResult booleanAlgebraPackage_dependencies_valid booleanAlgebraValidationResult ringTheoryPackage_dependencies_valid ringTheoryValidationResult peanoArithmeticPackage_dependencies_valid peanoArithmeticValidationResult fieldTheoryPackage_dependencies_valid fieldTheoryValidationResult orderTheoryPackage_dependencies_valid orderTheoryValidationResult pointSetTopologyPackage_dependencies_valid pointSetTopologyValidationResult graphTheoryPackage_dependencies_valid graphTheoryValidationResult numberTheoryPackage_dependencies_valid numberTheoryValidationResult measureTheoryPackage_dependencies_valid measureTheoryValidationResult realAnalysisPackage_dependencies_valid realAnalysisValidationResult functionalAnalysisPackage_dependencies_valid functionalAnalysisValidationResult probabilityTheoryPackage_dependencies_valid probabilityTheoryValidationResult algebraicGeometryPackage_dependencies_valid algebraicGeometryValidationResult informationTheoryPackage_dependencies_valid informationTheoryValidationResult linearAlgebraPackage_dependencies_valid linearAlgebraValidationResult homologicalAlgebraPackage_dependencies_valid homologicalAlgebraValidationResult differentialGeometryPackage_dependencies_valid differentialGeometryValidationResult computabilityTheoryPackage_dependencies_valid computabilityTheoryValidationResult modalLogicPackage_dependencies_valid modalLogicValidationResult universalAlgebraPackage_dependencies_valid universalAlgebraValidationResult combinatoricsPackage_dependencies_valid combinatoricsValidationResult gameTheoryPackage_dependencies_valid gameTheoryValidationResult homotopyTypeTheoryPackage_dependencies_valid homotopyTypeTheoryValidationResult dependentTypeTheoryPackage_dependencies_valid dependentTypeTheoryValidationResult simpleTypeTheoryPackage_dependencies_valid simpleTypeTheoryValidationResult affineGeometryPackage_dependencies_valid affineGeometryValidationResult algebraicTopologyPackage_dependencies_valid algebraicTopologyValidationResult ellipticGeometryPackage_dependencies_valid ellipticGeometryValidationResult metricSpacePackage_dependencies_valid metricSpaceValidationResult latticeTheoryPackage_dependencies_valid latticeTheoryValidationResult lieTheoryPackage_dependencies_valid lieTheoryValidationResult modelTheoryPackage_dependencies_valid modelTheoryValidationResult classicalPropositionalLogicPackage_dependencies_valid classicalPropositionalLogicValidationResult intuitionisticLogicPackage_dependencies_valid intuitionisticLogicValidationResult toposTheoryPackage_dependencies_valid toposTheoryValidationResult)
export Theory.Constraint (ConstraintStatus ConstraintGraph WellFormedGraph checkStatus)
export Theory.Constraint.Normalization (EquivalenceClass NormalizationState objIdOf findRep unionClasses normalizeStep detectContradiction normalize emptyState emptyState_classes emptyState_graph emptyState_not_contradictory detectContradiction_emptyState normalize_empty_classes normalize_empty_graph)
export Theory.Rewrite (Var Term Substitution emptySubst lookupSubst applySubst apply_emptySubst)
export Theory.Unification (UnificationProblem UnificationResult occursIn unifyStep unify mgu isUnifiable composeSubst isIdempotent unifyAll unify_empty unify_same_const unify_different_const unify_same_var unify_var_const mgu_of_unify_success mgu_of_unify_failure mgu_same_const mgu_different_const mgu_same_var mgu_var_const isUnifiable_same_const isUnifiable_different_const)
export Theory.Groebner (Monomial Polynomial zeroPoly monomialDegree monomialExp monomialMul monomialDivides monomialDiv monomialLCM MonomialOrder compareLex compareDegLex compareMonomial leadingTerm polyAdd polyNeg polySub polyMulMonomial reduceStep reduceFuel polyPairs sPolynomial buchbergerFuel buchberger idealMembership zeroPoly_eq_nil monomialDegree_nil monomialExp_nil monomialMul_nil_nil leadingTerm_zero polyPairs_nil buchberger_empty zero_in_empty_ideal)
export Theory.Reasoning (InferenceStep WellFormedStep ReasoningSoundness reasoning_soundness_skeleton)
export Theory.Proof (StepId ProofStep ProofObject Traceable ProofWellFormed)

-- 经典对照层导出
export Classical.Hilbert (IncidenceAxioms HilbertAxioms consistency_theorem)

end Lv00Formal
