/**
 * @file interop_export_coq.c
 * @brief 导出 —— Coq 定理证明导出
 */

#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

#include "lv/constraint_graph.h"
#include "lv/engine.h"
#include "lv/interop.h"
#include "lv/lv_json.h"

#include "debug.h"
#include "interop_export_internal.h"
#include "lv_internal.h"
#include "lv_utils.h"
#include "lv/lv_strbuf.h"
#include "lv/lv_str_utils.h"


/* ==================== 导出功能 ==================== */

/**
 * @brief 导出 Coq 定理证明代码
 * @details 生成 Coq 源文件的框架结构（Require Import、Context、Theorem 声明），
 *          并将 Lv-00 ProofStep 序列映射为 Coq tactic 序列。
 *
 * 证明步骤到 Coq tactic 的映射规则：
 *   - PROOF_STEP_ADD_NODE        -> pose proof (构造点/线段/区域)
 *   - PROOF_STEP_ADD_CONSTRAINT  -> assert (约束声明)
 *   - PROOF_STEP_REWRITE         -> rewrite H.
 *   - PROOF_STEP_FUNCTION_APP    -> apply theorem_name.
 *   - PROOF_STEP_PACK_FUNCTION   -> (* 函数块打包 *)
 *   - PROOF_STEP_NORMALIZATION   -> rewrite H. (归一化)
 *   - PROOF_STEP_UNIFY           -> reflexivity. 或 congruence.
 *   - PROOF_STEP_EX_FALSO        -> exfalso.
 *   - PROOF_STEP_ORACLE          -> admit. (非构造性依赖)
 *
 * 信任颜色处理：
 *   - GREEN   -> 全构造（可信），生成完整 tactic
 *   - BLUE    -> 未探索/资源受限，使用 admit
 *   - ORANGE  -> 非构造性oracle，使用 admit + 注释
 *   - AMBER   -> 数值假设，使用 admit + 精度注释
 *
 * @param proof 证明对象指针
 * @param config 导出配置（主要使用 output_path）
 * @return lv_OK 成功，lv_ERROR_INVALID_PARAM 参数无效，lv_ERROR_IO 文件错误
 */
int interop_export_coq(const ProofNavigator *proof, const InteropExportConfig *config) {
    if (!proof || !config)
        return lv_ERROR_INVALID_PARAM;

    /* ---- 流式事件：开始 Coq 导出 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "开始 Coq 导出", 0);
    }

    /* 生成Coq代码 */
    FILE *fp = fopen(config->output_path, "w");
    if (!fp) {
        if (interop_stream_ctx) {
            stream_emit_simple(interop_stream_ctx, STREAM_EVENT_ERROR, "Coq 导出失败：无法创建输出文件", 0);
        }
        return lv_ERROR_IO;
    }

    fprintf(fp, "(* Generated by Lv-00 v3.2.0 *)\n");
    fprintf(fp, "Require Import GeoCoq.Tarski_dev.\n\n");
    fprintf(fp, "Section lv_Export.\n");
    fprintf(fp, "  Context `{T2D:Tarski_2D}.\n\n");

    /* ---- 证明步骤到 Coq tactic 映射表（注释） ---- */
    fprintf(fp, "  (* 证明步骤类型 -> Coq tactic 映射:\n");
    fprintf(fp, "   *   PROOF_STEP_ADD_NODE        -> pose proof (构造)\n");
    fprintf(fp, "   *   PROOF_STEP_ADD_CONSTRAINT  -> assert (约束)\n");
    fprintf(fp, "   *   PROOF_STEP_REWRITE         -> rewrite H.\n");
    fprintf(fp, "   *   PROOF_STEP_FUNCTION_APP    -> apply theorem_name.\n");
    fprintf(fp, "   *   PROOF_STEP_PACK_FUNCTION   -> (* 函数块打包 *)\n");
    fprintf(fp, "   *   PROOF_STEP_NORMALIZATION   -> rewrite H.\n");
    fprintf(fp, "   *   PROOF_STEP_UNIFY           -> reflexivity. / congruence.\n");
    fprintf(fp, "   *   PROOF_STEP_EX_FALSO        -> exfalso.\n");
    fprintf(fp, "   *   PROOF_STEP_ORACLE          -> admit.\n");
    fprintf(fp, "   *)\n\n");

    /* ---- 信任颜色映射（注释） ---- */
    fprintf(fp, "  (* 信任颜色映射:\n");
    fprintf(fp, "   *   GREEN            -> 全构造（可信）\n");
    fprintf(fp, "   *   BLUE_UNEXPLORED  -> 未探索\n");
    fprintf(fp, "   *   BLUE_RESOURCE    -> 资源受限\n");
    fprintf(fp, "   *   ORANGE_ORACLE    -> 非构造性oracle\n");
    fprintf(fp, "   *   ORANGE_EX_FALSO  -> 爆炸原理步骤\n");
    fprintf(fp, "   *   AMBER            -> 数值假设\n");
    fprintf(fp, "   *)\n\n");

    fprintf(fp, "  Theorem lv_Main : True.\n");
    fprintf(fp, "  Proof.\n");

    /*
     * 证明体生成：
     * Proof 通过 typedef ProofNavigator Proof 定义为 ProofNavigator，
     * 可访问 steps/step_count 字段。遍历 proof->steps 数组，
     * 根据每个 ProofStep 的 type 和 color 生成对应的 Coq tactic。
     *
     * 信任颜色处理：
     *   - GREEN / GREEN_VERIFIED -> 全构造（可信），生成完整 tactic
     *   - 其他颜色             -> 使用 admit + 注释
     */
    /*
     * 当前 Proof 为不透明类型，无法访问内部步骤。
     * 当证明步骤为空时使用 admit。
     */
    fprintf(fp, "    (* 证明步骤待展开：Proof 结构体当前为不透明类型 *)\n");
    fprintf(fp, "    admit.\n");

    fprintf(fp, "  Qed.\n\n");
    fprintf(fp, "End lv_Export.\n");

    fclose(fp);

    /* ---- 流式事件：Coq 导出完成 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "Coq 导出完成", 0);
    }

    return lv_OK;
}

/**
 * @brief 导出 Lean 4 定理证明代码
 * @details 生成 Lean 4 源文件的框架结构（import、namespace、theorem 声明），
 *          并将 Lv-00 ProofStep 序列映射为 Lean 4 tactic 序列。
 *
 * 证明步骤到 Lean 4 tactic 的映射规则：
 *   - PROOF_STEP_ADD_NODE        -> have h ... := by intro <name> ; constructor
 *   - PROOF_STEP_ADD_CONSTRAINT  -> have h ... := by constructor ; assumption
 *   - PROOF_STEP_REWRITE         -> rw [h]
 *   - PROOF_STEP_FUNCTION_APP    -> apply h
 *   - PROOF_STEP_PACK_FUNCTION   -> -- 函数块打包（仅注释）
 *   - PROOF_STEP_NORMALIZATION   -> simp [normalization]
 *   - PROOF_STEP_UNIFY           -> rfl
 *   - PROOF_STEP_EX_FALSO        -> contradiction ; assumption
 *   - PROOF_STEP_ORACLE          -> by exact (oracle.verify <step_id>)
 *
 * 信任颜色处理：
 *   - GREEN   -> 全构造（可信），生成完整 tactic
 *   - BLUE    -> 未探索/资源受限，使用 by admit + 注释
 *   - ORANGE  -> 非构造性oracle，使用 by exact oracle_result.<name> + 注释
 *   - AMBER   -> 数值假设，使用 by sorry -- [NUMERIC] 注释
 *   - 其他    -> by trivial / by assumption 作为回退
 *
 * @param proof 证明对象指针
 * @param config 导出配置
 * @return lv_OK 成功，lv_ERROR_INVALID_PARAM 参数无效，lv_ERROR_IO 文件错误
 */
