/**
 * @file interop_export_canonical.c
 * @brief 导出 —— Canonical 导出
 */

#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

#include "lv/constraint_graph.h"
#include "lv/engine.h"
#include "lv/interop.h"
#include "lv/lv_file.h"
#include "lv/lv_json.h"

#include "lv/debug.h"
#include "interop_export_internal.h"
#include "lv/lv_internal.h"
#include "lv/lv_utils.h"
#include "lv/lv_strbuf.h"
#include "lv/lv_str_utils.h"
#include "lv/lv_xmacro.h"

/* ---- 节点类型 → 规范输出处理器查找表 ---- */
typedef void (*CanonicalNodeHandler)(FILE *fp, const GeomNode *node);

static void canonical_handler_port(FILE *fp, const GeomNode *node) {
    if (node->data.port) {
        fprintf(fp, " port_type=%s formal=%s poly=%s",
                (node->data.port->type == PORT_INPUT) ? "input" : "output",
                node->data.port->is_formal_param ? "true" : "false",
                node->data.port->is_polymorphic ? "true" : "false");
    }
}

static void canonical_handler_region(FILE *fp, const GeomNode *node) {
    fprintf(fp, " boundary_segments=%d", node->data.region.segment_count);
}

static void canonical_handler_circle(FILE *fp, const GeomNode *node) {
    fprintf(fp, " center=%d radius=%d", node->data.circle.center_node_id, node->data.circle.radius_node_id);
}

static void canonical_handler_func_block(FILE *fp, const GeomNode *node) {
    fprintf(fp, " internal=%d inputs=%d outputs=%d state=%d",
            node->data.func_block.internal_node_count,
            node->data.func_block.input_count,
            node->data.func_block.output_count,
            node->data.func_block.determinism_state);
}

static const CanonicalNodeHandler canonical_node_handlers[] = {
    [GEOM_PORT]         = canonical_handler_port,
    [GEOM_REGION]       = canonical_handler_region,
    [GEOM_CIRCLE]       = canonical_handler_circle,
    [GEOM_FUNCTION_BLOCK] = canonical_handler_func_block,
};

int interop_export_canonical(const ConstraintGraph *graph, const char *output_path) {
    if (!graph || !output_path)
        return lv_ERROR_INVALID_PARAM;

    FILE *fp = lv_file_open(output_path, "w");
    if (!fp)
        return lv_ERROR_IO;

    /* 输出规范表示 */
    fprintf(fp, "# Lv-00 Canonical Representation\n");
    fprintf(fp, "# Generated by Lv-00 v%s\n", lv_VERSION_STRING);
    fprintf(fp, "# Format: NodeType NodeID [Coordinates] TrustColor NamespaceDepth ParentBlockID\n");
    fprintf(fp, "#         ConstraintType ConstraintID ParticipantIDs...\n\n");

    /* 输出节点 */
    fprintf(fp, "NODES %d\n", graph->node_count);
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node)
            continue;

        /* 节点类型和ID */
        fprintf(fp, "%s %d", geom_type_name(node->type), node->id);

        /* 输出符号坐标 */
        fprintf(fp, " [");
        /* 内层坐标遍历：const 保护外层节点指针，只读遍历 */
        const int coord_cnt = node->coord_count;
        for (int j = 0; j < coord_cnt; j++) {
            if (j > 0)
                fprintf(fp, ", ");

            SymbolicCoord *coord = node->symbolic_coords[j];
            if (coord) {
                char *serialized = symbolic_coord_serialize(coord);
                if (serialized) {
                    fprintf(fp, "%s", serialized);
                    lv_free((void **) &serialized);
                } else {
                    /* 序列化失败时回退到数值表示；%.6g 为展示型精度（回退分支），
                     * 与主路径 symbolic_coord_serialize 的精确有理数输出不冲突 */
                    double val = symbolic_coord_to_double(coord);
                    fprintf(fp, "%.6g", val);
                }
            } else {
                fprintf(fp, "null");
            }
        }
        fprintf(fp, "]");

        /* 信任颜色 */
        fprintf(fp, " %s", trust_color_to_svg(node->trust));

        /* 命名空间深度和父块 */
        fprintf(fp, " ns=%d parent=%d", node->namespace_depth, node->parent_block_id);

        /* 类型特定信息 — 使用查找表（LV_DISPATCH_VOID 收敛边界/NULL/调用三行样板） */
        LV_DISPATCH_VOID(canonical_node_handlers, node->type, fp, node);

        fprintf(fp, "\n");
    }

    /* 输出约束 */
    fprintf(fp, "\nCONSTRAINTS %d\n", graph->constraint_count);
    for (int i = 0; i < graph->constraint_count; i++) {
        Constraint *c = graph->constraints[i];
        if (!c)
            continue;

        fprintf(fp, "%s %d", constraint_type_name(c->type), c->id);

        /* 参与者ID列表 */
        for (int j = 0; j < c->participant_count; j++) {
            fprintf(fp, " %d", c->participants[j]);
        }

        /* 模板ID（如果有） */
        if (c->template_id >= 0) {
            fprintf(fp, " template=%d", c->template_id);
        }

        fprintf(fp, "\n");
    }

    /* 输出邻接表（每个节点关联的约束） */
    fprintf(fp, "\nADJACENCY_LIST\n");
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node)
            continue;

        /* 查找涉及此节点的约束 */
        /* 256-sized stack array, size matches max_results — bound is correct */
        int related_indices[256];
        int related_count = graph_find_constraints_involving(graph, node->id, related_indices, 256);

        if (related_count > 0) {
            fprintf(fp, "NODE %d ->", node->id);
            for (int j = 0; j < related_count; j++) {
                Constraint *c = graph->constraints[related_indices[j]];
                if (c) {
                    fprintf(fp, " %s(%d)", constraint_type_name(c->type), c->id);
                }
            }
            fprintf(fp, "\n");
        }
    }

    lv_file_close(fp);

    return lv_OK;
}

/**
 * @brief 将约束图导出为 GeoJSON 格式文件
 * @details 动态生成 FeatureCollection，包含点类型节点（Point）和线段类型节点（LineString）
 *          及其坐标。点直接导出坐标，线段通过 INCIDENCE 约束查找端点坐标。
 * @param graph  约束图指针
 * @param config 导出配置（output_path 指定输出文件路径）
 * @return lv_OK 成功，lv_ERROR_INVALID_PARAM 参数无效，lv_ERROR_IO 文件错误
 */
