/**
 * @file interop_export_tikz.c
 * @brief 导出 —— TikZ 导出（含 fragment）
 */

#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

#include "lv/constraint_graph.h"
#include "lv/engine.h"
#include "lv/interop.h"
#include "lv/lv_json.h"

#include "debug.h"
#include "interop_export_internal.h"
#include "lv_internal.h"
#include "lv_utils.h"
#include "lv/lv_strbuf.h"
#include "lv/lv_str_utils.h"

/* ---- 约束类型 → TikZ 样式查找表 ---- */
typedef struct {
    const char *tikz_style;  /**< TikZ 绘制样式 */
} ConstraintTikzEntry;

static const ConstraintTikzEntry constraint_tikz_map[] = {
    [INCIDENCE]   = { "constraint" },
    [CONTAINMENT] = { "constraint, teal, densely dotted" },
    [ANGLE]       = { "constraint, purple, densely dashed" },
    [CONNECTION]  = { "connection" },
};

/* ---- 图例标志索引 ---- */
enum {
    LEGEND_POINT_IDX,
    LEGEND_LINE_IDX,
    LEGEND_REGION_IDX,
    LEGEND_BLOCK_IDX,
    LEGEND_PORT_IDX,
    LEGEND_NODE_COUNT
};

static const int node_legend_idx_map[] = {
    [GEOM_POINT]         = LEGEND_POINT_IDX,
    [GEOM_LINE_SEGMENT]  = LEGEND_LINE_IDX,
    [GEOM_REGION]        = LEGEND_REGION_IDX,
    [GEOM_CIRCLE]        = LEGEND_REGION_IDX,
    [GEOM_FUNCTION_BLOCK]= LEGEND_BLOCK_IDX,
    [GEOM_PORT]          = LEGEND_PORT_IDX,
};

enum {
    LEGEND_INCIDENCE_IDX,
    LEGEND_BETWEENNESS_IDX,
    LEGEND_INTERSECTION_IDX,
    LEGEND_CONTAINMENT_IDX,
    LEGEND_ANGLE_IDX,
    LEGEND_CONNECTION_IDX,
    LEGEND_CSTR_COUNT
};

static const int cstr_legend_idx_map[] = {
    [INCIDENCE]    = LEGEND_INCIDENCE_IDX,
    [BETWEENNESS]  = LEGEND_BETWEENNESS_IDX,
    [INTERSECTION] = LEGEND_INTERSECTION_IDX,
    [CONTAINMENT]  = LEGEND_CONTAINMENT_IDX,
    [ANGLE]        = LEGEND_ANGLE_IDX,
    [CONNECTION]   = LEGEND_CONNECTION_IDX,
};

/**
 * @brief 将约束图导出为 TikZ 文档（完整 LaTeX 文档，含文档框架）
 * @param graph  约束图指针
 * @param config 导出配置
 * @return lv_OK 成功，lv_ERROR_INVALID_PARAM 参数无效，lv_ERROR_IO 文件错误
 */
int interop_export_tikz(const ConstraintGraph *graph, const InteropExportConfig *config) {
    if (!graph || !config)
        return lv_ERROR_INVALID_PARAM;

    /* ---- 流式事件：开始 LaTeX/TikZ 导出 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "开始 LaTeX/TikZ 导出", 0);
    }

    /* 调用 tikz_fragment 生成 tikzpicture 内容，消除重复渲染循环 */
    size_t buf_size = 1024 * 1024; /* 1MB 缓冲区，足够容纳典型图形 */
    char *fragment_buf = (char *) lv_malloc(buf_size);
    if (!fragment_buf)
        return lv_ERROR_OUT_OF_MEMORY;

    int fragment_len = interop_export_tikz_fragment(graph, fragment_buf, buf_size);
    if (fragment_len < 0) {
        lv_free((void **) &fragment_buf);
        return fragment_len;
    }

    /* 打开输出文件 */
    FILE *fp = fopen(config->output_path, "w");
    if (!fp) {
        lv_free((void **) &fragment_buf);
        return lv_ERROR_IO;
    }

    /* LaTeX 文档头部 */
    (void) fprintf(fp, "%% Generated by Lv-00 v%s\n", lv_VERSION_STRING);
    (void) fprintf(fp, "%% TikZ geometry export\n\n");
    (void) fprintf(fp, "\\documentclass[tikz,border=10pt]{standalone}\n");
    (void) fprintf(fp, "\\usepackage{tikz}\n");
    (void) fprintf(fp, "\\usetikzlibrary{arrows.meta,shapes.geometric,positioning,calc}\n\n");
    (void) fprintf(fp, "\\begin{document}\n\n");

    /* 写入 tikzpicture 片段（含样式定义、所有渲染和图例） */
    fwrite(fragment_buf, 1, (size_t) fragment_len, fp);
    fprintf(fp, "\n\n");

    /* 文档尾部 */
    (void) fprintf(fp, "\\end{document}\n");

    fclose(fp);
    lv_free((void **) &fragment_buf);

    /* ---- 流式事件：LaTeX/TikZ 导出完成 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "LaTeX/TikZ 导出完成", 0);
    }

    return lv_OK;
}

/**
 * @brief 将约束图导出为 TikZ 片段（不含文档框架）
 * @details 仅输出 \\begin{tikzpicture}...\\end{tikzpicture} 片段，
 *          可直接嵌入已有的 LaTeX 文档。包含样式定义、节点渲染、
 *          约束渲染、符号坐标标签和自动图例。
 * @param graph 约束图指针
 * @param output 输出缓冲区
 * @param size 缓冲区大小
 * @return 实际写入字符数（不含终止符），失败返回负数
 */
int interop_export_tikz_fragment(const ConstraintGraph *graph, char *output, size_t size) {
    if (!graph || !output || size == 0)
        lv_RETURN_ERROR(lv_ERROR_INVALID_PARAM, "interop_export_tikz_fragment: invalid parameters");

    /* ---- 流式事件：开始 TikZ 片段导出 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "开始 TikZ 片段导出", 0);
    }

    /* 使用 snprintf 逐步写入缓冲区 */
    int total = 0;
    int remaining = (int) size;

#define TIKZ_FRAG_PRINTF(...)                                              \
    do {                                                                   \
        int n = snprintf(output + total, (size_t) remaining, __VA_ARGS__); \
        if (n < 0)                                                         \
            lv_RETURN_ERROR(lv_ERROR_IO, "tikz_fragment: snprintf failed");\
        if (n >= remaining) {                                              \
            total += remaining - 1;                                        \
            remaining = 1;                                                 \
        } else {                                                           \
            total += n;                                                    \
            remaining -= n;                                                \
        }                                                                  \
    } while (0)

    /* TikZ 样式定义和 tikzpicture 开始 */
    TIKZ_FRAG_PRINTF("%% Generated by Lv-00 v%s (TikZ fragment)\n", lv_VERSION_STRING);
    TIKZ_FRAG_PRINTF("\\begin{tikzpicture}[\n");
    TIKZ_FRAG_PRINTF("    point/.style={circle, fill, inner sep=1.5pt},\n");
    TIKZ_FRAG_PRINTF("    line/.style={thick},\n");
    TIKZ_FRAG_PRINTF("    region/.style={fill opacity=0.3, thick},\n");
    TIKZ_FRAG_PRINTF("    constraint/.style={dashed, thin, gray},\n");
    TIKZ_FRAG_PRINTF("    block/.style={draw, rounded corners, minimum width=2cm, minimum height=1cm, thick},\n");
    TIKZ_FRAG_PRINTF("    port/.style={circle, draw, inner sep=2pt, fill=white},\n");
    TIKZ_FRAG_PRINTF("    label/.style={font=\\small},\n");
    TIKZ_FRAG_PRINTF("    connection/.style={-{Stealth[length=5pt]}, thick, orange}\n");
    TIKZ_FRAG_PRINTF("]\n\n");

    /* ---- 渲染区域（底层） ---- */
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node || node->type != GEOM_REGION)
            continue;
        if (node->data.region.segment_count < 3)
            continue;

        const char *color = trust_color_to_tikz(node->trust);

        TIKZ_FRAG_PRINTF("    %% Region id=%d\n", node->id);
        TIKZ_FRAG_PRINTF("    \\draw[region, fill=%s] ", color);

        int first_point = 1;
        for (int s = 0; s < node->data.region.segment_count; s++) {
            GeomNode *seg = node->data.region.boundary_segments[s];
            if (seg && seg->type == GEOM_LINE_SEGMENT && seg->coord_count >= 4) {
                double sx1 = symbolic_coord_to_double(seg->symbolic_coords[0]);
                double sy1 = symbolic_coord_to_double(seg->symbolic_coords[1]);
                if (first_point) {
                    TIKZ_FRAG_PRINTF("(%.2f, %.2f)", sx1, sy1);
                    first_point = 0;
                } else {
                    TIKZ_FRAG_PRINTF(" -- (%.2f, %.2f)", sx1, sy1);
                }
            }
        }
        TIKZ_FRAG_PRINTF(" -- cycle;\n");
    }

    /* ---- 渲染函数块 ---- */
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node || node->type != GEOM_FUNCTION_BLOCK)
            continue;
        if (node->coord_count < 2)
            continue;

        double bx = symbolic_coord_to_double(node->symbolic_coords[0]);
        double by = symbolic_coord_to_double(node->symbolic_coords[1]);

        const char *color = trust_color_to_tikz(node->trust);

        TIKZ_FRAG_PRINTF("    %% Function Block id=%d\n", node->id);
        TIKZ_FRAG_PRINTF(
            "    \\node[block, draw=%s, fill=%s, fill opacity=0.15] "
            "at (%.2f, %.2f) {FB\\_%d};\n",
            color, color, bx, by, node->id);
    }

    /* ---- 渲染线段 ---- */
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node || node->type != GEOM_LINE_SEGMENT)
            continue;
        if (node->coord_count < 4)
            continue;

        double x1 = symbolic_coord_to_double(node->symbolic_coords[0]);
        double y1 = symbolic_coord_to_double(node->symbolic_coords[1]);
        double x2 = symbolic_coord_to_double(node->symbolic_coords[2]);
        double y2 = symbolic_coord_to_double(node->symbolic_coords[3]);

        const char *color = trust_color_to_tikz(node->trust);

        TIKZ_FRAG_PRINTF("    %% Line Segment id=%d\n", node->id);
        TIKZ_FRAG_PRINTF(
            "    \\draw[line, %s] (%.2f, %.2f) -- (%.2f, %.2f) "
            "node[midway, above, label] {seg\\_%d};\n",
            color, x1, y1, x2, y2, node->id);
    }

    /* ---- 渲染端口 ---- */
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node || node->type != GEOM_PORT)
            continue;
        if (node->coord_count < 2)
            continue;

        double px = symbolic_coord_to_double(node->symbolic_coords[0]);
        double py = symbolic_coord_to_double(node->symbolic_coords[1]);

        const char *color = trust_color_to_tikz(node->trust);
        const char *port_type_str = (node->data.port && node->data.port->type == PORT_INPUT) ? "in" : "out";

        TIKZ_FRAG_PRINTF("    %% Port id=%d type=%s\n", node->id, port_type_str);
        TIKZ_FRAG_PRINTF("    \\node[port, draw=%s] (port%d) at (%.2f, %.2f) {};\n", color, node->id, px, py);
        TIKZ_FRAG_PRINTF(
            "    \\node[label, %s, font=\\tiny] at (%.2f, %.2f) "
            "{%s\\_%d};\n",
            color, px, py + 0.3, port_type_str, node->id);
    }

    /* ---- 渲染点（带符号坐标标签） ---- */
    for (int i = 0; i < graph->node_count; i++) {
        GeomNode *node = graph->nodes[i];
        if (!node || node->type != GEOM_POINT)
            continue;
        if (node->coord_count < 2)
            continue;

        double px = symbolic_coord_to_double(node->symbolic_coords[0]);
        double py = symbolic_coord_to_double(node->symbolic_coords[1]);

        const char *color = trust_color_to_tikz(node->trust);

        TIKZ_FRAG_PRINTF("    %% Point id=%d\n", node->id);
        TIKZ_FRAG_PRINTF("    \\node[point, %s] (P%d) at (%.2f, %.2f) {};\n", color, node->id, px, py);

        /* 使用符号坐标序列化作为标签（如果坐标可用） */
        if (node->symbolic_coords && node->symbolic_coords[0] && node->symbolic_coords[1]) {
            char *sx = symbolic_coord_serialize(node->symbolic_coords[0]);
            char *sy = symbolic_coord_serialize(node->symbolic_coords[1]);
            if (sx && sy) {
                TIKZ_FRAG_PRINTF(
                    "    \\node[label, above=2pt of P%d] "
                    "{$P_{%d}\\!\\left(%s,\\, %s\\right)$};\n",
                    node->id, node->id, sx, sy);
            } else {
                TIKZ_FRAG_PRINTF("    \\node[label, above=2pt of P%d] {$P_{%d}$};\n", node->id, node->id);
            }
            lv_free((void **) &sx);
            lv_free((void **) &sy);
        } else {
            TIKZ_FRAG_PRINTF("    \\node[label, above=2pt of P%d] {$P_{%d}$};\n", node->id, node->id);
        }
    }

    /* ---- 渲染约束 ---- */
    for (int i = 0; i < graph->constraint_count; i++) {
        Constraint *c = graph->constraints[i];
        if (!c || c->participant_count < 2)
            continue;

        TIKZ_FRAG_PRINTF("    %% Constraint id=%d type=%s\n", c->id, constraint_type_name(c->type));

        GeomNode *p0 = graph_get_node_by_id(graph, c->participants[0]);
        GeomNode *p1 = graph_get_node_by_id(graph, c->participants[1]);
        if (!p0 || !p1)
            continue;
        if (p0->coord_count < 2 || p1->coord_count < 2)
            continue;

        double x0 = symbolic_coord_to_double(p0->symbolic_coords[0]);
        double y0 = symbolic_coord_to_double(p0->symbolic_coords[1]);
        double x1 = symbolic_coord_to_double(p1->symbolic_coords[0]);
        double y1 = symbolic_coord_to_double(p1->symbolic_coords[1]);

        switch (c->type) {
            case BETWEENNESS: {
                double mx = (x0 + x1) / 2.0;
                double my = (y0 + y1) / 2.0;
                TIKZ_FRAG_PRINTF(
                    "    \\node[label, purple, font=\\itshape] at (%.2f, %.2f) "
                    "{B(%d, %d",
                    mx, my, c->participants[0], c->participants[1]);
                if (c->participant_count >= 3) {
                    TIKZ_FRAG_PRINTF(", %d", c->participants[2]);
                }
                TIKZ_FRAG_PRINTF(")};\n");
                break;
            }

            case INTERSECTION:
                TIKZ_FRAG_PRINTF("    \\draw[constraint, purple] (%.2f, %.2f) -- (%.2f, %.2f);\n", x0, y0, x1, y1);
                TIKZ_FRAG_PRINTF("    \\node[circle, draw=purple, inner sep=1pt] at (%.2f, %.2f) {};\n", x0, y0);
                break;

            default: {
                /* 使用查找表 */
                const ConstraintTikzEntry *entry = &constraint_tikz_map[c->type];
                TIKZ_FRAG_PRINTF("    \\draw[%s] (%.2f, %.2f) -- (%.2f, %.2f);\n",
                                 entry->tikz_style, x0, y0, x1, y1);
                break;
            }
        }
    }

    /* ---- 图例（Legend） ---- */
    {
        bool has_node_legend[LEGEND_NODE_COUNT] = {false};
        bool has_cstr_legend[LEGEND_CSTR_COUNT] = {false};

        for (int i = 0; i < graph->node_count; i++) {
            GeomNode *n = graph->nodes[i];
            if (!n)
                continue;
            /* 使用查找表替代 switch */
            if ((int)n->type >= 0 && (size_t)n->type < sizeof(node_legend_idx_map) / sizeof(node_legend_idx_map[0]))
                has_node_legend[node_legend_idx_map[n->type]] = true;
        }
        for (int i = 0; i < graph->constraint_count; i++) {
            Constraint *c = graph->constraints[i];
            if (!c)
                continue;
            /* 使用查找表替代 switch */
            if ((int)c->type >= 0 && (size_t)c->type < sizeof(cstr_legend_idx_map) / sizeof(cstr_legend_idx_map[0]))
                has_cstr_legend[cstr_legend_idx_map[c->type]] = true;
        }

        int legend_rows = 0;
        for (int i = 0; i < LEGEND_NODE_COUNT; i++) {
            if (has_node_legend[i])
                legend_rows++;
        }
        for (int i = 0; i < LEGEND_CSTR_COUNT; i++) {
            if (has_cstr_legend[i])
                legend_rows++;
        }

        if (legend_rows > 0) {
            TIKZ_FRAG_PRINTF("\n    %% Legend\n");
            TIKZ_FRAG_PRINTF(
                "    \\matrix[draw, fill=white, fill opacity=0.85, "
                "anchor=south east, column sep=4pt, row sep=2pt, "
                "font=\\scriptsize, inner sep=4pt]\n");
            TIKZ_FRAG_PRINTF("    at (current bounding box.south east) {\n");

            int row = 0;
            if (has_node_legend[LEGEND_POINT_IDX]) {
                TIKZ_FRAG_PRINTF("        \\node[point] {}; & \\node {Point}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_node_legend[LEGEND_LINE_IDX]) {
                TIKZ_FRAG_PRINTF("        \\draw[line] (0,0) -- (0.5,0); & \\node {Line Segment}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_node_legend[LEGEND_REGION_IDX]) {
                TIKZ_FRAG_PRINTF("        \\draw[region, fill=blue!20] (0,0) rectangle (0.5,0.3); & \\node {Region}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_node_legend[LEGEND_BLOCK_IDX]) {
                TIKZ_FRAG_PRINTF(
                    "        \\node[block, minimum width=0.5cm, minimum height=0.3cm] {}; & \\node {Function Block}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_node_legend[LEGEND_PORT_IDX]) {
                TIKZ_FRAG_PRINTF("        \\node[port] {}; & \\node {Port}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_cstr_legend[LEGEND_INCIDENCE_IDX]) {
                TIKZ_FRAG_PRINTF("        \\draw[constraint] (0,0) -- (0.5,0); & \\node {Incidence}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_cstr_legend[LEGEND_BETWEENNESS_IDX]) {
                TIKZ_FRAG_PRINTF("        \\node[purple, font=\\itshape] {B}; & \\node {Betweenness}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_cstr_legend[LEGEND_INTERSECTION_IDX]) {
                TIKZ_FRAG_PRINTF(
                    "        \\draw[constraint, purple] (0,0) -- (0.5,0); "
                    "\\node[circle, draw=purple, inner sep=0.5pt] at (0.25,0) {}; "
                    "& \\node {Intersection}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_cstr_legend[LEGEND_CONTAINMENT_IDX]) {
                TIKZ_FRAG_PRINTF(
                    "        \\draw[constraint, teal, densely dotted] (0,0) -- (0.5,0); & \\node {Containment}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }
            if (has_cstr_legend[LEGEND_CONNECTION_IDX]) {
                TIKZ_FRAG_PRINTF("        \\draw[connection] (0,0) -- (0.5,0); & \\node {Connection}; ");
                if (++row < legend_rows)
                    TIKZ_FRAG_PRINTF("\\\\\n");
            }

            TIKZ_FRAG_PRINTF("    };\n");
        }
    }

    TIKZ_FRAG_PRINTF("\n\\end{tikzpicture}\n");

#undef TIKZ_FRAG_PRINTF

    /* 确保以 null 终止 */
    if (total >= (int) size) {
        output[size - 1] = '\0';
        return (int) size - 1; /* 截断但仍返回写入量 */
    }
    output[total] = '\0';

    /* ---- 流式事件：TikZ 片段导出完成 ---- */
    if (interop_stream_ctx) {
        stream_emit_simple(interop_stream_ctx, STREAM_EVENT_INFO, "TikZ 片段导出完成", 0);
    }

    return total;
}

/**
 * @brief 将约束图导出为规范表示（Canonical）文本文件
 * @details 包含节点（类型、ID、坐标、信任色、命名空间深度、父块 ID、类型特定信息）、
 *          约束（类型、ID、参与者列表、模板 ID）和邻接表。
 * @param graph       约束图指针
 * @param output_path 输出文件路径
 * @return lv_OK 成功，lv_ERROR_INVALID_PARAM 参数无效，lv_ERROR_IO 文件错误
 */
